### ISSUE TITLE
Text thinks "Refill Kit" is as wide as "Refill Ki"

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/build-a-molecule#1]
This causes the text to overshoot the button UI, and it looks ugly (gray is shaded over where the Text bounds thinks it exists):

![bam-refill-bounds](https://f.cloud.github.com/assets/480878/1119775/bb18a3dc-1a84-11e3-8a42-e9937769d995.PNG)

**Comment by Denz1994** [comment]
The refill button has been changed to look like the image below:

![image](https://user-images.githubusercontent.com/13894380/69236422-791e8d00-0b61-11ea-8819-d5f558567e5a.png)

There is enough spacing in the margins to account for the button's text size. Closing.
