### ISSUE TITLE
Repeated interaction with 3D button causes reload

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/build-a-molecule#110]
**Test device**
Windows 7 laptop
**Operating System**
Windows 7
**Browser**
Chrome 
**Problem description**
For https://github.com/phetsims/QA/issues/459

When the 3D button is pressed multiple times in rapid succession, the sim will eventually face an error and need to reload.
**Steps to reproduce**
1. Create any molecule (O2 is quickest)
2.  Repeatedly and Rapidly click the 3D button
**Visuals**
![2019-11-21ThreeDBttnBldMlce](https://user-images.githubusercontent.com/54685448/69383005-b2e0b800-0c75-11ea-831a-81e2cbc8a79a.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Molecule‬
URL: https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.23/phet/build-a-molecule_all_phet.html
Version: 0.0.0-dev.23 2019-11-20 23:29:39 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
Language: en-US
Window: 1366x625
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 32 varying: 32 uniform: 256
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by Denz1994** [comment]
This failure was being triggered due to the browser refreshing when too many ThreeNodes are created (see [here](https://stackoverflow.com/questions/21548247/clean-up-threejs-webgl-contexts) for more info). Reserving a single dialog node in the BAMView restricts the sim to build only one ThreeNode. 

The above commit should have solved this.

**Comment by Denz1994** [comment]
Can you confirm this isn't happening in this [dev version ](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.28/phet/build-a-molecule_en_phet.html?dev) @KatieWoe?

**Comment by KatieWoe** [comment]
Looks good in the dev version
