### ISSUE TITLE
Atoms float in the bucket

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#112]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/459
When atoms in a bucket are taken from the bottom layer the atoms above it do not fall, leaving them floating in mid air.
**Steps to reproduce**
1. Go to the last screen (occurs on any, but this is easier)
2. Pick a bucket with two layers
3. Remove the bottom layer of atoms and put them in the play area.

**Visuals**
![FloatH](https://user-images.githubusercontent.com/41024075/69385548-f8ed4a00-0c7c-11ea-83b1-a30d167aa347.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Molecule‬
URL: https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.23/phet/build-a-molecule_all_phet.html
Version: 0.0.0-dev.23 2019-11-20 23:29:39 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by Denz1994** [comment]
`SphereBucket.removeParticle(particle, skipLayout)` indicates that its second argument should determine whether the layout is handled automatically. Currently, this is set to false and layout is handled by BAM code. 

This should be refactored, but it requires the atom.destinationProperty be updated accordingly.

**Comment by Denz1994** [comment]
This can be fixed by adjusting the `skipLayout` parameter from above. Also, the `Atom2.isSeparatingProperty` can be removed because it was restricting stepping the Atom to update the position property based on its destination property.

@KatieWoe Can you confirm that the atoms don't float in the buckets anymore? Also, the remaining atoms should fill the space that a removed/dragged atom was occupying. This [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.68/phet/build-a-molecule_en_phet.html) can be checked.

**Comment by KatieWoe** [comment]
The floating issue seems fixed. I did notice some other odd behavior of the remaining atoms in bucket though. Sometimes one will jump to a higher position, move to the side, rather than drop down, and become unable to be stacked back up.
![randomshift](https://user-images.githubusercontent.com/41024075/78812493-bbb5fa00-7988-11ea-9625-3e41016eab2c.gif)
![shiftovernodrag](https://user-images.githubusercontent.com/41024075/78812494-bce72700-7988-11ea-9eb5-b582f537cb70.gif)
![shiftup](https://user-images.githubusercontent.com/41024075/78812501-bd7fbd80-7988-11ea-8ca3-ffc8595a02fc.gif)

**Comment by Denz1994** [comment]
Note to self: `Bucket.addParticleNearestOpen()` may need to be used where the restoring bucket state isn't important. `Bucket.placeAtom()` should distinguish this using an argument.

**Comment by Denz1994** [comment]
Adjusting `Bucket.placeAtom()` worked well for handling the odd behavior described above. @KatieWoe can you verify in this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.69/phet/build-a-molecule_en_phet.html)?

**Comment by KatieWoe** [comment]
Looks much better now. You can't really restack the atoms, like in the second gif, but you can move them around now, so I think this is probably satisfactory.

**Comment by Denz1994** [comment]
In the java version, a user could stack the atoms until the exited the carousel and spilled into the play area. I don't think we want this behavior but I'll let @arouinfar decide and close. @arouinfar Could you review and close if this looks good?

Here is the Java version: 
![image](https://user-images.githubusercontent.com/13894380/78825766-7f959000-79ae-11ea-87b7-08ddbaa428f9.png)

**Comment by Denz1994** [comment]
@arouinfar and I went over this and the stacking behavior mentioned above is something we don't want. As it stands we can't intentionally stack atoms anymore. Closing this issue.
