### ISSUE TITLE
Early loading screen delay

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#114]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/459
Note that this is documented/recorded from one of our faster platforms. The sim has so far shown acceptable if slow load times. However, the progress bar does not seem to move at all until the very end. This gives the impression for a few seconds that the sim is not loading at all.

**Visuals**
![severalseconds](https://user-images.githubusercontent.com/41024075/69441054-2aaaf300-0d07-11ea-968d-f2b8a946447c.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Molecule‬
URL: https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.23/phet/build-a-molecule_all_phet.html
Version: 0.0.0-dev.23 2019-11-20 23:29:39 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by Denz1994** [comment]
@KatieWoe Could you compare this loading time to a lower-end device?

**Comment by KatieWoe** [comment]
6 or so seconds on Win 7 IE. Acceptable for IE, but still looks like nothing as progressing as above.

**Comment by Denz1994** [comment]
The stall at the beginning is due the data set being loaded. From the design meeting on 11/27/19 and https://github.com/phetsims/build-a-molecule/issues/109#issuecomment-559224124 we aren't going to proceed with truncating the data set.

If the only issue is that it looks like the sim isn't loading, I would argue that the sim loading bar has a subtle dimming and brightening to its outline and that is enough indication that the sim is still loading.

@arouinfar Maybe it would be worth deciding if this is a problem during interviews?

**Comment by arouinfar** [comment]
The gif doesn't look unreasonable to me. I understand that the load time is even longer for win7 devices, but I still think it's acceptable. Windows 7 is a month out from its end-of-life, and the devices running it are likely old and slow at this point. It shouldn't be particularly surprising to users that the sim loads slowly. I think we can go ahead and close this @Denz1994.
