### ISSUE TITLE
Large memory test and leak

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#115]
For https://github.com/phetsims/QA/issues/459
Start: 136 MB
1 min: 224
2 min: 282
3 min: 333
4 min: 381
5 min: 426
6 min: 471
7 min: crash

**Comment by loganbraywork** [comment]
For https://github.com/phetsims/QA/issues/479
Start: 156 MB
10 Minute interval: 658 MB
After the snapshot was taken and saved (which took about 20 minutes to finish) the sim crashed without starting up again and began to cause immense slowdowns on my PC.

**Comment by Denz1994** [comment]
The latest memory test was recorded over with 15 min intervals (Chrome Version 80.0.3987.122, macOS Catalina 10.15.1). It looks like there is significant improvements but there are some TODOs left in the code related to optimization, so we may be able to squeeze out a better performance.

Here are my results:
![image](https://user-images.githubusercontent.com/13894380/76452473-93e26f00-63a7-11ea-9aa3-1619d03a92cf.png)


@KatieWoe Could you run a similar test to the original [post](https://github.com/phetsims/build-a-molecule/issues/115#issue-527296129)? Have the results improved from your initial test?  Try this dev version [here](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.60/phet/build-a-molecule_en_phet.html).

**Comment by Denz1994** [comment]
Also assigning @loganbraywork since he reported in this issue as well. Whoever gets to it first, should be fine to test it.

**Comment by KatieWoe** [comment]
Results:
Start: 109 MB
1 min: 145 MB
2 min: 164 MB
3 min: 183 MB
4 min: 196 MB
5 min: 209 MB
6 min: 219 MB
7 min: Memory tab crashed and closed

**Comment by Denz1994** [comment]
@KatieWoe What device and browser where you using?

**Comment by KatieWoe** [comment]
Windows 10 Chrome Laptop

**Comment by Denz1994** [comment]
Additional memory leaks have been identified and removed in the above commits. Can @KatieWoe do another memory test similar to https://github.com/phetsims/build-a-molecule/issues/115#issuecomment-597901038?

**Comment by KatieWoe** [comment]
From Master:
Start: 109 MB
1 min: 118 MB
2 min: 120 MB
3 min: 121 MB
4 min: 121 MB
5 min: 122 MB
6 min: 123 MB
7 min: 125 MB
8 min: 126 MB
9 min: 126 MB
10 min: 127 MB

Looks good

**Comment by Denz1994** [comment]
The latest memory test is looking good. We can close this one.
