### ISSUE TITLE
Invisible answer box?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#119]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/459
There seems to be an area on the right of the play area in the last screen that molecules can't be placed of used. They move as if an answer box is there, even though there isn't.
**Steps to reproduce**
1. Go to the last screen
2. Drag something far to the right and let go, note the apparent edge of the play area the object returns to.
3. Click the object or drag it slightly to the left

**Visuals**
![doublejump](https://user-images.githubusercontent.com/41024075/69454188-d57cda80-0d22-11ea-9cfe-c613cb6651c1.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Molecule‬
URL: https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.23/phet/build-a-molecule_all_phet.html
Version: 0.0.0-dev.23 2019-11-20 23:29:39 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
Similar behavior:
![slightlyrelated](https://user-images.githubusercontent.com/41024075/69454359-46bc8d80-0d23-11ea-854a-35c97a8e1b73.gif)

**Comment by KatieWoe** [comment]
Happens a bit on the left side of the screen too.

**Comment by Denz1994** [comment]
There are playAreaBounds that are set on each screen which the molecules animate to. The 3rd screen needs a different set of bounds that extends a bit further to the right.

**Comment by Denz1994** [comment]
This https://github.com/phetsims/build-a-molecule/commit/cc2f23358680e3fd8229d70a7caf50154031a299 should have fixed the exaggerated bounds on the right side. Could @arouinfar review the size of the play area bounds?

**Comment by Denz1994** [comment]
Also, the refill and resetAllButton (on 3rd screen) are included in these bounds. This means there can be overlap with the atoms when dragged to the corner. Maybe the playAreaBounds should be a custom Shape instead of rectangular bounds.

**Comment by arouinfar** [comment]
@Denz1994 things are looking good in master. I don't think we need to do anything special for the `ResetAllButton`. If the button is obscured, it's because a user put something in front of it. They can simply drag the molecule out of the way. There's also precedent for this sort of behavior in `expression-exchange`. There, coins can be dragged in front of the `ResetAllButton`.

![image](https://user-images.githubusercontent.com/8419308/69582822-a2428180-0f96-11ea-8f96-e94f2922dcef.png)

**Comment by Denz1994** [comment]
@KatieWoe This invisible box bugginess should be fixed in this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.28/phet/build-a-molecule_en_phet.html?dev).

**Comment by KatieWoe** [comment]
Looks good in the dev version
