### ISSUE TITLE
Reset all crash behavior

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#122]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/459
Under certain conditions, resetting the sim causes the sim to crash and the page needs to be refreshed.
**Steps to reproduce**
1. Go to either the first or second screen
2. Finish one collection
3. Either go back to a previous collection and return to the current one or reset the sim
4. Drag an atom out of the bucket
5. Reset the sim

**Visuals**
![crashbug](https://user-images.githubusercontent.com/41024075/69457995-97d07f80-0d2b-11ea-999a-326af91e0199.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Molecule‬
URL: https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.23/phet/build-a-molecule_all_phet.html?profiler
Version: 0.0.0-dev.23 2019-11-20 23:29:39 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by KatieWoe** [comment]
Console Error
![console](https://user-images.githubusercontent.com/41024075/69459548-3dd1b900-0d2f-11ea-96ca-d441272440e5.png)

**Comment by Denz1994** [comment]
Commit dc895aa57224af1e128248abfe662262fae237e5 might have fixed this. Can you confirm this is fixed in this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.33/phet/build-a-molecule_en_phet.html) @KatieWoe ?

Note: You can use the query parameter `?easyMode`. It will allow you to go to the next collection after one completed molecule. You will need to refresh the sim if you don't go to the next collection though.

**Comment by KatieWoe** [comment]
Other than https://github.com/phetsims/build-a-molecule/issues/135 this seems solved

**Comment by Denz1994** [comment]
Closing this one. Further issues will be addressed in #135.
