### ISSUE TITLE
Resetting does not reset collection

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#123]
For https://github.com/phetsims/QA/issues/459
When you reset on the first or second screen after having completed at least one collection, resetting leaves you with a situation where it says you are on collection one, but the questions and atoms are of the one you were on.
![resetsamesim](https://user-images.githubusercontent.com/41024075/69458144-f1d14500-0d2b-11ea-8e01-7f47ddc75022.gif)

**Comment by Denz1994** [comment]
This was fixed as a part of https://github.com/phetsims/build-a-molecule/issues/121#issuecomment-566130544. Closing this one.
