### ISSUE TITLE
Crash when manipulating previous collection

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#125]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/459
When you manipulate atoms in a previous collection and return to the current one, graphical bugs result and a crash happens if you try to answer a question.
**Steps to reproduce**
1. Go to the first or second screen
2. Finish a collection
3. Go back to a previous collection and drag atoms out and around (may need to leave them out)
4. Go back to the current one.
5. Manipulate atoms
6. Try to answer problem

**Visuals**
![morecrashbugs](https://user-images.githubusercontent.com/41024075/69460522-a883f400-0d31-11ea-8803-fbe7c0cd10d9.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Molecule‬
URL: https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.23/phet/build-a-molecule_all_phet.html?profiler
Version: 0.0.0-dev.23 2019-11-20 23:29:39 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by Denz1994** [comment]
`KitCollectionList.switchTo(collection)` is being called when the yellow arrow buttons hit. This is a good place to start. Perhaps the kitPanel and kitPlayAreaNode should keep track of the current collection? Standby for more information.

**Comment by Denz1994** [comment]
This was fixed during https://github.com/phetsims/build-a-molecule/issues/121#issuecomment-566130544. Closing this one.
