### ISSUE TITLE
Reset Button overlaps answers box

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#126]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/459
On the second screen, the answer box gets bigger due to added text as you add molecules. It starts to overlap with the orange reset all button.

**Visuals**
![toobig](https://user-images.githubusercontent.com/41024075/69462536-7e810080-0d36-11ea-814f-b65c4f82f486.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Molecule‬
URL: https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.23/phet/build-a-molecule_all_phet.html?profiler
Version: 0.0.0-dev.23 2019-11-20 23:29:39 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by Denz1994** [comment]
There was some extra padding that was removed for the resetAllButton positioning. Will release a new dev version to compare.

**Comment by Denz1994** [comment]
This should be fixed in this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.28/phet/build-a-molecule_en_phet.html?dev) @KatieWoe.

**Comment by KatieWoe** [comment]
looks good in dev version
