### ISSUE TITLE
Boron ate the Hydrogen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#127]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/459
The image that appears in the answer box for Borane looks like hydrogen is inside the boron rather than around it.

**Visuals**
What it looks like in the sim:
![isit](https://user-images.githubusercontent.com/41024075/69466891-171d7d80-0d43-11ea-8642-b567224bc97f.png)
What it should look like:
![image](https://user-images.githubusercontent.com/41024075/69466901-20a6e580-0d43-11ea-8c8f-24727348812f.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Molecule‬
URL: https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.23/phet/build-a-molecule_all_phet.html
Version: 0.0.0-dev.23 2019-11-20 23:29:39 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by lmulhall-phet** [comment]
You are Boron me with these silly issue titles, Katie.

**Comment by arouinfar** [comment]
Looks like a bug to me @Denz1994

**Comment by Denz1994** [comment]
This is fixed for Boron but a more general solution is explained [here](https://github.com/phetsims/build-a-molecule/issues/111#issuecomment-575132079).

**Comment by Denz1994** [comment]
Can you confirm this was fixed in this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.42/phet/build-a-molecule_all_phet.html) @KatieWoe?

**Comment by Denz1994** [comment]
Can you confirm this isn't a problem in this [dev version ](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.42/phet/build-a-molecule_all_phet.html) @KatieWoe?

**Comment by KatieWoe** [comment]
Looks much better now. This is what the Borane molecule looks like now:
![nowlookslike](https://user-images.githubusercontent.com/41024075/72910893-6b6abc80-3cf6-11ea-98a6-55a4250383a2.png)

**Comment by Denz1994** [comment]
What do you think @arouinfar? A more general solution is described [here](https://github.com/phetsims/build-a-molecule/issues/111#issuecomment-575132079).

**Comment by arouinfar** [comment]
@Denz1994 looks good! The appearance is a close match for the Java version.
