### ISSUE TITLE
Long strings not handled consistently and lead to graphical problems

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#128]
For https://github.com/phetsims/QA/issues/459
![loooooooooong](https://user-images.githubusercontent.com/41024075/69467835-f9521780-0d46-11ea-823e-7f2597a0fa16.png)
![notgreatlong](https://user-images.githubusercontent.com/41024075/69467837-f9521780-0d46-11ea-8a8e-7527b48c6803.png)

**Comment by Denz1994** [comment]
Maxwidths have been adjusted for strings. I'll release a new dev version for comparison.

**Comment by Denz1994** [comment]
Can @KatieWoe confirm that the strings look okay in this [dev version
](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.28/phet/build-a-molecule_en_phet.html?dev)?

**Comment by KatieWoe** [comment]
This does indeed look better in the dev version.
