### ISSUE TITLE
source code directory store structure doesn't conform to PhET standards

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/build-a-molecule#129]
While investigating https://github.com/phetsims/build-a-molecule/issues/100, I noticed source code directory store structure doesn't conform to PhET standards. The js/ directory should have a subdirectory for each screen (single/, multiple/, larger/) and a common/ subdirectory for code shared by 1 or more screens.  Instead, it has model/, view/, and screen/.  This will fail code review, and should be reorganized.

**Comment by Denz1994** [comment]
The js directory now contains common and screen-specific directories. The relevant paths have been updated in all the `require` import statements. Closing this one.
