### ISSUE TITLE
unconventional names for ScreenView subclasses

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/build-a-molecule#130]
Noticed while investigating #100.

PhET coding convention is to name ScreenView subclasses as `{{NAME}}ScreenView`.  This sim does not follow that convention. `BAMView` and `MoleculeCollectingView` should be renamed.

**Comment by Denz1994** [comment]
Files have been refactored in the above commits. 
- BAMView -> BAMScreenView
- MoleculeCollectingView -> MoleculeCollectingScreenView

Closing.
