### ISSUE TITLE
Organic Nomenclature

### ISSUE THREAD

**Issue by arouinfar** [phetsims/build-a-molecule#131]
According to teacher tips, we should be showing the common name for organic molecules, where applicable. However, there are some quirks in the current behavior.

A notable example would be that Acetic Acid Methyl Ester displays a common name, but isopropyl alcohol does not (propan-2-ol). 
<img width="376" alt="BAM-nomenclature" src="https://user-images.githubusercontent.com/8419308/69755594-c8daf680-1115-11ea-9b5c-321ff643d388.png">
<img width="253" alt="BAM-nomenclature-3" src="https://user-images.githubusercontent.com/8419308/69755595-c8daf680-1115-11ea-84a6-b931e12cd947.png">

There some other edge cases like “n-propane” where the “n” doesn’t actually carry any meaningful information about the structure (unlike n-butane vs. isobutane). 
<img width="219" alt="BAM-nomenclature-2" src="https://user-images.githubusercontent.com/8419308/69755657-e740f200-1115-11ea-8b7e-4d1801ff8c89.png">

We will need to add a few more overrides to the nomenclature, but I should first consult some HS/AP textbooks to see how organic nomenclature is handled.

**Comment by Denz1994** [comment]
These names used for the molecules can be adjusted relatively easily.  Isopropyl alcohol and propane show the suggested names from above. If there are any other molecules that should be renamed we should detail in this issue. 

@arouinfar Can you confirm this looks okay in this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.42/phet/build-a-molecule_all_phet.html). Also what other molecules should be adjusted.

**Comment by arouinfar** [comment]
Thanks @Denz1994. After playing around quite a bit with the simulation, I couldn't find any other organic molecules that need a nomenclature override. 

I would, however, recommend that we use "isopropanol" for the override, since it's more parallel to "methanol" and "ethanol".

**Comment by Denz1994** [comment]
Override provided for `isopropyl alcohol` -> `isopropanol `. If this looks good then I'll leave for you to close @arouinfar.

![image](https://user-images.githubusercontent.com/13894380/73277700-8b97f100-41b8-11ea-842d-1aa29b468dee.png)

**Comment by arouinfar** [comment]
👍
