### ISSUE TITLE
On Chrome OS, buckets too large, spill over into next page of carousel

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/build-a-molecule#132]
<b>Test Device</b>

Lovelace

<b>Operating System</b>

Chrome OS 79.0.3945.42

<b>Browser</b>

Chrome

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/459.

<b>Visuals</b>

![1](https://user-images.githubusercontent.com/31285590/70194161-acfbc580-16be-11ea-8b40-2a8fa1e43435.png)
![2](https://user-images.githubusercontent.com/31285590/70194167-b422d380-16be-11ea-9a65-1dde4bdc7b2c.png)
![3](https://user-images.githubusercontent.com/31285590/70194176-b84ef100-16be-11ea-9375-00ef6e3e19be.png)

**Comment by Denz1994** [comment]
From https://github.com/phetsims/build-a-molecule/issues/134#issuecomment-572635601
>

**Comment by Denz1994** [comment]
Can @KatieWoe verify this isn't an issue anymore in this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.38/phet/build-a-molecule_all_phet.html)?

**Comment by KatieWoe** [comment]
There is a very, very minor overlap of the buckets in the third page of the carousel on the third screen. So the second and forth pages have slight dots on the edge. Seen on Win 10 Chrome. Super nitpicky.
![here2](https://user-images.githubusercontent.com/41024075/72384315-6a280700-36da-11ea-9df2-55714e0615a4.png)
![here4](https://user-images.githubusercontent.com/41024075/72384317-6ac09d80-36da-11ea-93e4-f8838180489a.png)

**Comment by Denz1994** [comment]
Very good eye @KatieWoe. This is literally a pixel polish. Should be fixed in this [dev](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.39/phet/build-a-molecule_all_phet.html)

**Comment by KatieWoe** [comment]
This issue looks good on that dev version

**Comment by KatieWoe** [comment]
I'll also look at a few other platforms just in case today.

**Comment by KatieWoe** [comment]
All looks good

**Comment by Denz1994** [comment]
Thanks for checking. Closing this one.
