### ISSUE TITLE
Push atoms into the answer box

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#133]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
Found in https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.28/phet/build-a-molecule_en_phet.html?dev while testing fixed issues. Fairly minor. It is possible to push atoms into the answer area even though they would normally be pushed out.
**Steps to reproduce**
1. Make part of a molecule
2. Put it beside the answer box
3. Cut the molecule apart

**Visuals**
![jumpinthebox](https://user-images.githubusercontent.com/41024075/70364549-31c71a80-184a-11ea-8e0f-f36da16c5bb4.gif)

Troubleshooting information:

<dtails>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Molecule‬
URL: https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.28/phet/build-a-molecule_en_phet.html?dev
Version: 0.0.0-dev.28 2019-12-05 16:25:33 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by Denz1994** [comment]
Related to #120

**Comment by Denz1994** [comment]
This may have been corrected due to changing play area bounds in #120. Can you confirm this isn't an issue in this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.42/phet/build-a-molecule_all_phet.html)  @KatieWoe?

**Comment by KatieWoe** [comment]
This does seem fixed, but I noticed that the molecules move back to the play area in two disjointed steps.
![doublejump](https://user-images.githubusercontent.com/41024075/72851932-37e25080-3c6a-11ea-9456-3891aa17c76d.gif)

**Comment by Denz1994** [comment]
Right this disjointed action is due to using both the `kit.separationMoleculeDestinations()` and `Twixt` animation support. We can get away with using just the Kit's model to handle the bounds for the molecules along with constraining them to those kit bounds. 

I removed support for the animation behavior so we are solely relying on `kit.js` to do this for us. 

The behavior has been updated in this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.44/phet/build-a-molecule_en_phet.html). Can you review @KatieWoe?

**Comment by loganbraywork** [comment]
Appears to be fixed

**Comment by Denz1994** [comment]
Nice closing this one.
