### ISSUE TITLE
Reset All inconsistent collection. First reset won't let you continue

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#135]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
Found when checking https://github.com/phetsims/build-a-molecule/issues/122. Seems unrelated to that issue.
When you reset the first or second screen after completing a collection, the first time it will reset to show the first collection. If you hit reset again it shows you Collection 1, but it will be the collection you were on before, with those atoms and molecules. If you try to complete the collection after the first reset you will not get the continue dialog after completing it.
**Steps to reproduce**
1. Go to the first or second screen
2. Complete a collection
3. When in the second collection, hit reset all
4. Try to complete the first collection again
5. Hit reset all a second time

**Visuals**
![firstreset](https://user-images.githubusercontent.com/41024075/70929876-3e3d3700-1ff1-11ea-9e25-9224cfe258a0.png)
![newresetbehavior](https://user-images.githubusercontent.com/41024075/70929885-4301eb00-1ff1-11ea-8efa-783a59a5d85a.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Molecule‬
URL: https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.33/phet/build-a-molecule_en_phet.html
Version: 0.0.0-dev.33 2019-12-16 16:05:03 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
Now that I think of it, it may be related to https://github.com/phetsims/build-a-molecule/issues/121

**Comment by Denz1994** [comment]
I think this has been fixed in the above commit. It can be verified on the latest [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.38/phet/build-a-molecule_en_phet.html).

**Comment by Denz1994** [comment]
Can you confirm this is fixed @KatieWoe?

**Comment by lmulhall-phet** [comment]
> If you hit reset again it shows you Collection 1, but it will be the collection you were on before, with those atoms and molecules.

This is fixed.

> If you try to complete the collection after the first reset you will not get the continue dialog after completing it.

This is not fixed.

**Comment by Denz1994** [comment]
I see. I wasn't resetting the allFilledProperty along with the flag determining if the dialog has shown once on the BAMScreenSubtypes. This change has been made in this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.40/phet/build-a-molecule_all_phet.html).

**Comment by loganbraywork** [comment]
Appears to be fully fixed now

**Comment by Denz1994** [comment]
Nice. Closing this one.
