### ISSUE TITLE
CT value is not a member of Enumeration [object Object]

### ISSUE THREAD

**Issue by zepumph** [phetsims/build-a-molecule#136]
This CT bug is occurring because validation for enumerations currently expects to only ever have one Enumeration for a set of keys. This is up for discussion over in https://github.com/phetsims/phet-core/issues/79 but in the mean time I think this assertion for this sim has an easy solution.

**Comment by zepumph** [comment]
@Denz1994 please review, do you think this is an alright change?

**Comment by Denz1994** [comment]
Minor formatting changes in https://github.com/phetsims/build-a-molecule/commit/825842a3a0708c1951c6ddd30f200ccbecec884b, but I used a similar solution for https://github.com/phetsims/masses-and-springs/issues/349. I haven't seen this pop up on CT either.

**Comment by Denz1994** [comment]
CT has been clear for about half a day's worth of cycles. I'm going to close this one.
