### ISSUE TITLE
[Multiple Screen] Molecules overlap 3D button in collection

### ISSUE THREAD

**Issue by arouinfar** [phetsims/build-a-molecule#138]
It is possible for the molecules to overlap the 3D button in the collection. Molecules should only be allowed to fill the space to the left of the button, which means they will need to be scaled down a bit.
<img width="219" alt="BAM" src="https://user-images.githubusercontent.com/8419308/72183834-37190700-33ac-11ea-9d3f-945c3865c3fc.png">

Here's what it looked like in Java.
<img width="178" alt="BAM-Java" src="https://user-images.githubusercontent.com/8419308/72183836-37190700-33ac-11ea-99d1-cdb58af01a53.png">

**Comment by Denz1994** [comment]
The layout boxes' content has been centered on the Multiple Screen. Can you confirm this is fixed in this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.42/phet/build-a-molecule_all_phet.html) @arouinfar?

**Comment by arouinfar** [comment]
Looks good @Denz1994!
