### ISSUE TITLE
Intermediate pixel polishes

### ISSUE THREAD

**Issue by Denz1994** [phetsims/build-a-molecule#139]
This BAM [dev](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.39/phet/build-a-molecule_all_phet.html) has come across far enough where some pixel polishing could be addressed.

I'll note some points that I think are worth review but will leave to the design team for further input:

- [x]  NextCollectionButton color scheme.
- [x]  The color scheme of atoms, considering their view in the 3d representation dialog box
- [x]  The overall presentation of the AllFilled box (shows when a collection is completed)
- [x]  The zoom scale of molecules, rotational speed, and drag sensitivity in the 3d molecule dialog.
- [x]  Position of resetAllButton and refill button 

Note: There is an `?easyMode` query parameter to fill collections easily.

Assigning @ariel-phet for intial review.

**Comment by Denz1994** [comment]
Raising priority. Many bug related issues have been addressed. It was suggested that we should include pixel polishes in the next round of dev testing.

**Comment by arouinfar** [comment]
For the ResetAllButton, we could bottom-align it with the body of the carousel and right-align it with the collection panel.
![image](https://user-images.githubusercontent.com/8419308/73104937-dcf06980-3eb4-11ea-89b1-d95bb21fb317.png)
![image](https://user-images.githubusercontent.com/8419308/73104956-e8dc2b80-3eb4-11ea-886b-0bd7c25de30f.png)

**Comment by ariel-phet** [comment]
@Denz1994 here are some polishes I would like:

- [ ] Home screen and Navbar icons should probably use the sim play area background color, this will give them good contrast on the the homescreen and navbar, and follows the general convention of other sims

- [ ] For the "Single" screen, reduce the size of the water molecule slightly (it is just a bit big in the navbar now, perhaps about 15% reduction

- [ ] Implement @arouinfar ResetAllButton positioning suggestion from above

- [ ] For the "Your Molecules" Panel, and the AllFilled box, match the corner radius to the radius used on the Carousel 

- [ ] For the AllFilled box, center the next collection button in the negative space below the "You completed your collection" line (like shown below)
![allfilled](https://user-images.githubusercontent.com/4051174/73141005-70a07200-403c-11ea-888b-9b7e2b8e8b48.PNG)

- [ ] As long a the color scheme used for the atoms is the same as Java, no need to change (I believe those follow some sort of chemistry standard)

- [ ] For the 3d view, I don't think we want to put the play/pause button between the radio buttons (translation issues for one thing). Probably something more like I suggest below, but perhaps wait until @arouinfar weights in, I will have two questions for her in the following comment:

![allfilled](https://user-images.githubusercontent.com/4051174/73141117-8a8e8480-403d-11ea-8210-b47367a47b06.PNG)

**Comment by ariel-phet** [comment]
@arouinfar two questions for you

- It might be better in the 3d window to just have icons for "Space Filling" and "Ball and Stick" view, that would reduce issues we could run into with layout and translation and such. Thoughts?

- I was thinking on the playground screen it might be nice if the bottom of the buckets stayed aligned as you flip the carousel back and forth, on some carousel pages that would leave a fair bit of white space at top. Does that bother you as is, thoughts on aligning the buckets across carousel pages?

**Comment by arouinfar** [comment]
> It might be better in the 3d window to just have icons for "Space Filling" and "Ball and Stick" view, that would reduce issues we could run into with layout and translation and such. Thoughts?

I like this idea, though I wonder if it's important to include the actual names of the representations of molecular structure. I've pinged @emily-phet to ask her thoughts.

Here's a rough mockup of what the dialog could look like. 
![image](https://user-images.githubusercontent.com/8419308/73201408-309dc580-40f6-11ea-833c-aeb82c01b07e.png)

> I was thinking on the playground screen it might be nice if the bottom of the buckets stayed aligned as you flip the carousel back and forth, on some carousel pages that would leave a fair bit of white space at top. Does that bother you as is, thoughts on aligning the buckets across carousel pages?

@ariel-phet I think the tallest bucket is vertically centered in the carousel, with the other buckets bottom-aligned. The most noticeable contrast is between the 3rd page (containing a tall stack of chlorine) and the 5th page (relatively short bucket contents).
![image](https://user-images.githubusercontent.com/8419308/73200450-0814cc00-40f4-11ea-93dd-7912f6073003.png)
![image](https://user-images.githubusercontent.com/8419308/73200653-76598e80-40f4-11ea-8963-2c08f456ad22.png)


I am fine with the current behavior, though I can see that the vertical jumping could look a bit odd. My guess is the current alignment approach is likely the easiest, but if you feel strongly about the alignment, then I would suggest using the bucket position on the 3rd page everywhere within the carousel.

**Comment by arouinfar** [comment]
> As long a the color scheme used for the atoms is the same as Java, no need to change (I believe those follow some sort of chemistry standard)

@Denz1994 we've defined the various colors for atoms in [Nitroglycerin/Element](https://github.com/phetsims/nitroglycerin/blob/master/js/Element.js#L71). I believe BAM is already using this. While similar to the Java colors, we did end up making some changes to improve colorblind contrast in https://github.com/phetsims/nitroglycerin/issues/12.

**Comment by ariel-phet** [comment]
@Denz1994 let's leave the bucket alignment as is for now on the third screen.

Let's also wait until we get some chemist input from @emily-phet if we should consider icons or not.

**Comment by Denz1994** [comment]
Most of the changes have been committed. Just awaiting input from @emily-phet on text vs. icon representation for the radio button.

> @Denz1994 we've defined the various colors for atoms in Nitroglycerin/Element. I believe BAM is already using this. 

This is true. There would be nothing to change here.

**Comment by emily-phet** [comment]
Weighing in on text vs icon:
- I think it's a good idea to consider. 
- There are situations where a teacher would appreciate the use of the written out form, but it's pretty secondary to the goals of the sim overall, so not a deal-breaker in its own right (in my mind).
- I think the important thing is for the icons to convey "generic" representations. Keep in mind, any molecule representation is itself a complex representation embedded many chemistry ideas and not simple for chemistry students to interpret (*particularly when they're in a mode where they feel like they *should* know what it means!). In Molecule Shapes, we use purple and white (or is it silver...@arouinfar would know) to convey "generic" molecules. I suggest considering using that same convention in this case, and probably a diatomic, or simple linear triatomic to further simplify the example. 
-If/when the sim has description, the words would be provided that way, and in a self-voicing future of PhET sims, may be available that way without a screen reader as well...so may be even less of an issue to use icons over text. 

Let me know if that helps!

**Comment by arouinfar** [comment]
@emily-phet thanks for reviewing! Let's move forward with the iconic radio buttons.

> n Molecule Shapes, we use purple and white (or is it silver...@arouinfar would know) to convey "generic" molecules. I suggest considering using that same convention in this case, and probably a diatomic, or simple linear triatomic to further simplify the example.

This is great to keep in mind. I think a diatomic molecule with the generic coloring would work nicely. 

@Denz1994 the generic molecules in Molecule Shapes  are purple/white:
<img src="https://user-images.githubusercontent.com/8419308/73580806-2bb57a80-4444-11ea-93e7-1103d32ac774.png" width=300>

`rgb( 159, 102, 218 )`
`rgb( 255, 255, 255)`

I cobbled together a rough mockup using screenshots (ignore the atom colors). I chose a molecule with a double bond so there'd be a bit more contrast between the two options.
![image](https://user-images.githubusercontent.com/8419308/73580709-bea1e500-4443-11ea-9edf-7eec83246d44.png)

**Comment by Denz1994** [comment]
@arouinfar Can you check this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.53/phet/build-a-molecule_all_phet.html) to make sure this behavior and appearance are in the correct direction? 

Note: I still need to add the radio buttons. Will need @jonathanolson advice to get pass assertion check for the parent type when rendering icons.

**Comment by arouinfar** [comment]
@Denz1994 that's exactly what I was thinking!

For future reference, icons in the dev version look like this:
![image](https://user-images.githubusercontent.com/8419308/73688942-614ba500-468a-11ea-88bd-66190a3de6f7.png)

**Comment by Denz1994** [comment]
During status meeting on 02/06/20, @arouinfar asked to be reassigned to this issue for additional input on the design of the radio buttons. Is this correct @arouinfar?

**Comment by arouinfar** [comment]
@Denz1994 here's a mockup of the RadioButtonGroup.
![image](https://user-images.githubusercontent.com/8419308/74557865-544a7380-4f1e-11ea-9ce3-00b5c47a0ebd.png)

**Comment by Denz1994** [comment]
Master now includes the `RadioButtonGroup` for the two models. Can you review @arouinfar?

![image](https://user-images.githubusercontent.com/13894380/74665985-abdf1e00-516e-11ea-9190-f61d7c419ec8.png)

**Comment by arouinfar** [comment]
Looks great @Denz1994!
