### ISSUE TITLE
Multiple molecules overlap 3D button when in collection

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/build-a-molecule#140]
**Test device**
Hanson
**Operating System**
Windows 10
**Browser**
Chrome
**Problem description**
In the multiple molecules screen, collected molecules have a chance to  overlap the 3D button when in the collection.
**Steps to reproduce**
1. Enter Multiple screen
2. Complete the hydrogen collection
3. Observe hydrogen molecules in the completed collection
**Visuals**
[_Build a Molecule_.pdf](https://github.com/phetsims/build-a-molecule/files/4068233/_Build.a.Molecule_.pdf)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Molecule‬
URL: https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.38/phet/build-a-molecule_en_phet.html
Version: 0.0.0-dev.38 2020-01-09 14:39:10 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
Language: en-US
Window: 1280x610
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by Denz1994** [comment]
Related to #138

**Comment by Denz1994** [comment]
Can you confirm this isn't a problem any longer in this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.42/phet/build-a-molecule_all_phet.html) @loganbraywork?

**Comment by loganbraywork** [comment]
Appears to be fixed

**Comment by Denz1994** [comment]
Thanks for verifying. Closing this issue.
