### ISSUE TITLE
String test long causes issues with the 3D view of a molecule

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/build-a-molecule#142]
**Test device**
Windows 7 Laptop
**Operating System**
Windows 7
**Browser**
Firefox
**Problem description**
The long string test causes the 3D view of the molecule to shift to the right
**Steps to reproduce**
1. Use the StringTest=long query parameter
2. Complete a molecule
3. Enter the 3D view screen
**Visuals**
![2020-01-16StrnTstlngBldMlcl](https://user-images.githubusercontent.com/54685448/72564256-97a4ba00-386c-11ea-96bb-58eb35775526.JPG)

<details>
<summary> <b> Troubleshooting information:
</summary>!!!!! DO NOT EDIT !!!!!
Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.38/phet/build-a-molecule_en_phet.html?stringTest=long
Version: 0.0.0-dev.38 2020-01-09 14:39:10 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
Language: en-US
Window: 1366x654
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by JRomero0613** [comment]
The "x" seen in the upper right hand corner that closes the window is present when the string is extra long, but can not be seen in other scenarios when the strings are shorter.

**Comment by Denz1994** [comment]
Changes have been applied to the radio button texts. Also, the close button's color has been switched to `white`. Can you confirm this looks good in this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.42/phet/build-a-molecule_all_phet.html)?

**Comment by loganbraywork** [comment]
Appears to be fixed

**Comment by Denz1994** [comment]
Cool. Closing.
