### ISSUE TITLE
Atoms Can Enter Areas They Aren't Supposed To When Spread Out

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/build-a-molecule#143]
For the latest build of Build-a-Molecule (dev 40) atoms that are spread out can be moved to an area where they would normally not be allowed (i.e. part of the atom is in the bucket area). To replicate this behavior build a vertical molecule right above the bucket area or a horizontal molecule right next to the collection area. Spread the molecule using the spread button or by cutting it. The molecule will become spread out and the atom closer to the area will be slightly in the area. Normally if you place an atom in the same spot that the atoms are moved to it will not allow it to stay there (i.e. if any part of the atom is on the bucket area the atom will be returned to the bucket). I have attached a screenshot that illustrates the behavior on both the bucket area and the collection area.
![Screen Shot 2020-01-16 at 3 31 03 PM](https://user-images.githubusercontent.com/30352536/72568363-3503ec00-3875-11ea-9f47-59632b3a2e8d.png)

**Comment by Denz1994** [comment]
I believe this is related to #120, but has been fixed due to changing the playAreaBounds. Can you test @JRomero0613  if this has been fixed in this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.42/phet/build-a-molecule_all_phet.html)?

**Comment by loganbraywork** [comment]
Appears to be fixed

**Comment by Denz1994** [comment]
Thanks, closing this one.
