### ISSUE TITLE
Using two fingers on touch enabled devices causes atom spread in molecules

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/build-a-molecule#144]
**Test device**
Hanson
**Operating System**
Windows 10
**Browser**
Chrome
**Problem description**
Similar to https://github.com/phetsims/build-a-molecule/issues/118 but can lead to buggier behavior if two fingers continue to be used.
When two fingers are used on a built molecule it causes the atoms to change distance from each other  but the molecule to not break apart which can lead to further buggy behavior
**Steps to reproduce**
1. Enter the lab screen
2. Build a molecule
3. Using a touch enabled computer, manipulate both atoms of the molecule simultaneously using two fingers
**Visuals**
![molecules lightedge](https://user-images.githubusercontent.com/54685448/72647207-385eac80-3935-11ea-9ec9-c66f5c6ab08f.gif)

<details><summary>Troubleshooting information:
</summary>!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Molecule‬
URL: http://phettest.colorado.edu/build-a-molecule/build-a-molecule_en.html?ea&brand=phet
Version: 0.0.0-dev.40 (require.js)
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
Language: en-US
Window: 1280x610
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by loganbraywork** [comment]
Can also cause a crash similar to https://github.com/phetsims/build-a-molecule/issues/141 if spread out molecules are placed into the buckets

**Comment by Denz1994** [comment]
Can you confirm this is fixed in this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.59/phet/build-a-molecule_all_phet.html) @loganbraywork?

**Comment by Denz1994** [comment]
Adding @KatieWoe to this confirm this issue, due to QA devices being moved between members. This [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.67/phet/build-a-molecule_en_phet.html) should have the same fixes from above. Atoms shouldn't be separated when dragging with two fingers.

**Comment by KatieWoe** [comment]
This issue seems fixed from what I can tell in that dev version

**Comment by Denz1994** [comment]
Nice. Closing.
