### ISSUE TITLE
Matt should be present for the next RC deploy

### ISSUE THREAD

**Issue by mattpen** [phetsims/build-a-molecule#145]
See https://github.com/phetsims/perennial/issues/146#issuecomment-577354683.

I'd like to be present for the next RC deploy so I can investigate permissions issues on bayes if needed.

**Comment by Denz1994** [comment]
Note for self: Make sure that no RC deploys interfere with https://github.com/phetsims/build-a-molecule/issues/167.

**Comment by mattpen** [comment]
> Note for self: Make sure that RC deploys don't interfere with #167.

RC deploys should be fine.  Its just production deploys that could be problematic as there could be some filesystem level conflicts.

**Comment by chrisklus** [comment]
from 06/18/20 dev meeting:

@mattpen and @Denz1994 will find time to overlap on this

**Comment by Denz1994** [comment]
@mattpen @jonathanolson and I created a successful deploy with no issues. Closing this one.

**Comment by Denz1994** [comment]
Correction: We did run into problems with `build-a-molecule_en.html` not committing after being built. @jonathanolson mentioned this was related to https://github.com/phetsims/perennial/issues/172 and the last call to `gitIsClean()` in `updateHTMLVersion.js`. This was sorted out after manually committing and pushing this file on Master.
