### ISSUE TITLE
If cursor is in play area, should it be knife icon?

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/build-a-molecule#146]
If cursor is in play area, should it be a knife icon? This way the user will know that you can slice the molecules. Or maybe change it to a knife when you're slicing the molecules...

**Comment by Denz1994** [comment]
I think this is being further discussed as a part of https://github.com/phetsims/build-a-molecule/issues/52.

**Comment by Denz1994** [comment]
We are removing the slice feature from the sim. See #52. 

Closing this issue.
