### ISSUE TITLE
unable to create 4-carbon chain

### ISSUE THREAD

**Issue by arouinfar** [phetsims/build-a-molecule#148]
Noticed during #131 

It should be possible to connect four carbons in a straight chain, but that's not currently possible. 
![4-c](https://user-images.githubusercontent.com/8419308/73103813-2b503900-3eb2-11ea-9218-6bc5cc6910e9.gif)

However, it is possible to connect them in this arrangement
![image](https://user-images.githubusercontent.com/8419308/73103886-55a1f680-3eb2-11ea-8871-2bed6166f1ae.png)

**Comment by Denz1994** [comment]
This issue is due to `structuresData.js` not containing the valid structure for `C4` as-built above.

_More details regarding implementation:_

The allowed structures are validated every time and atom is attempted to bond (see `Kit.attemptToBondMolecule`). From this, the attempted bond is validated against the master list `structuresData.js` of allowed structures via a hash string. If the structure that is built from the molecule bonds (`StrippedMolecule`) doesn't exist in that master list, then it is rejected.

The workaround is to amend the `structuresData.js` with the entry for `C4` as it is built and bonded above. @jonathanolson didn't see why this structure shouldn't exist and perhaps this is related to the need to regenerate new data for the structures (similar to #158). There is a sanity check to prevent looping but that didn't seem promising when removing the check (see `MoleculeStructure.hasLoopsOrIsDisconnected`)

@arouinfar Can you confirm that `C4` can be created in master?

**Comment by Denz1994** [comment]
Note: The above measures to prevent looping were implemented to prevent structures like this.

![image](https://user-images.githubusercontent.com/13894380/74294247-4244b700-4d0b-11ea-844c-0f8dd6d0b550.png)

**Comment by arouinfar** [comment]
@Denz1994 something's still not quite right.  I can connect 4 carbons in a straight line, but I'm then unable to attach any hydrogens to the carbon chain UNLESS I first attach something else like an N or O.

![C4](https://user-images.githubusercontent.com/8419308/74379813-aae07200-4da5-11ea-990b-c69d581b6d99.gif)

I'm also finding cases like this that I can make in Java, but not in HTML5:
<img src="https://user-images.githubusercontent.com/8419308/74379651-72409880-4da5-11ea-9c6d-e493538a2870.png" width=300>

However, the data for this molecule can be found in OtherMoleculesData.js
`acetic acid ethyl ester|C4H8O2|8857`

**Comment by Denz1994** [comment]
The structure data has been inputted for the above-mentioned molecules. Can you confirm this is the case on Master @arouinfar?

**Comment by arouinfar** [comment]
Things are generally working now @Denz1994. I'm seeing some buggy behavior that I'm not 100% sure how to consistently reproduce. Occasionally, I am unable to create large molecules, and it seems like it happens if I've used the button to cut all bonds 

![image](https://user-images.githubusercontent.com/8419308/77959060-3c8f3a80-7293-11ea-8b08-eb9c88b31563.png)

Can you play around with it a bit and see if you can figure out what's going on? I also recommend having QA bang away on this issue during the next dev test.

**Comment by arouinfar** [comment]
@Denz1994 something strange is going on. I'm currently trying to verify #169, and was trying to build acetic ethyl acid ester from https://github.com/phetsims/build-a-molecule/issues/148#issuecomment-585432259. I was able to build it earlier today on master (see the screenshot in #169), but now I don't seem to be able to. 

My current procedure is:
1. Open Playground
2. Make `C-C-O-C` by dragging particles out of the bucket and immediately connecting them to the chain.
3. Try to connect a 4th carbon to the end of the chain to make `C-C-O-C-C` but it bumps away like it's an illegal structure.

**Comment by Denz1994** [comment]
Regarding https://github.com/phetsims/build-a-molecule/issues/148#issuecomment-606233607:

A testing cycle may look something like this:

1. Build a specific molecule from a set of large molecules, while tracking the order by which the molecule was built.
2. Break the molecule using the blue arrowed button
3. Reconstruct the molecule from step 1, using a different build order.
4. Repeat 1-3 for the remaining set of large molecules.

_*The point is the order of the build path shouldn't matter to construct the molecule_

I've tried these steps with the below molecules and can't replicate the concerns brought up https://github.com/phetsims/build-a-molecule/issues/148#issuecomment-606233607. @arouinfar Should we add more molecules to test? Also, what do you think about the above-proposed testing cycle?

**Comment by Denz1994** [comment]
@arouinfar Could you try this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.68/phet/build-a-molecule_en_phet.html) for reviewing https://github.com/phetsims/build-a-molecule/issues/148#issuecomment-606283587. The build order for `acetic ethyl acid ester` shouldn't matter in this build.

**Comment by Denz1994** [comment]
@arouinfar and I revisited the issue mentioned in https://github.com/phetsims/build-a-molecule/issues/148#issuecomment-606233607. I wasn't able to reproduce locally, and @arouinfar thought this may be related to chrome caching an older version of BAM. We thought a QA member could take a look at this.

@KatieWoe **Summary**: The order by which a molecule is built shouldn't matter. It was noted that occasionally building a molecule in a specific order fails. I've given some instructions on https://github.com/phetsims/build-a-molecule/issues/148#issuecomment-611099900 to help test this issue. Could you try these steps on a few large molecules and determine if the build order affects if they can be built or not?

**Comment by KatieWoe** [comment]
You can create https://github.com/phetsims/build-a-molecule/issues/148#issuecomment-584965693 in the above dev version @Denz1994

**Comment by Denz1994** [comment]
Were you able to replicate https://github.com/phetsims/build-a-molecule/issues/148#issuecomment-611099900 @KatieWoe?

**Comment by KatieWoe** [comment]
No, but I haven't been able to dedicate a lot of testing time to it due to other tests.

**Comment by arouinfar** [comment]
@Denz1994 @KatieWoe I am unable to reproduce the exact problem described in https://github.com/phetsims/build-a-molecule/issues/148#issuecomment-606283587, but I'm running into a related problem. It seems like the issue is localized to molecules containing chains like `C-C-O-C-C` or `C-O-C-C-C`. After building these chains, I am unable to attach any hydrogens to the carbons, despite there being several structures in the database that contain these chains.

Procedure:
1. Playground screen, Kit 2
2. Create `C-C-O-C-C`, adding atoms in order from left-to-right.
3. Try to add a hydrogen to a carbon. Regardless of the carbon, it will be repulsed.
4. Add an oxygen to the 2nd or 3rd carbon. For example:
![image](https://user-images.githubusercontent.com/8419308/80035637-95767b00-84ad-11ea-9549-87f178ae6ef8.png)
5. Carbon-hydrogen bonding is now possible.

**Comment by Denz1994** [comment]
I misinterpreted the check that prevents https://github.com/phetsims/build-a-molecule/issues/148#issuecomment-584965693. This was allowed in the legacy version as well. 

The concern was regarding a user no knowing what atoms are bonded in the example in https://github.com/phetsims/build-a-molecule/issues/148#issuecomment-584965693. However, with the addition of the cut targets (yellow circles), it clearly shows what atoms are bonded. I don't think this is an issue. Tagging @arouinfar to confirm.

**Comment by Denz1994** [comment]
Also, the above commits should have fixed the order dependent bonding problem that was mentioned by @arouinfar above. Can you test in this dev version @arouinfar?

@jonathanolson and I did some intense deep-diving into the visitor arrays in `checkEquivalency()`. It looks like I was removing the incorrect items from the visited atoms causing these false equivalencies.

**Comment by arouinfar** [comment]
This appears to be fixed in dev.74 @Denz1994.

If the sim is in a good place, it would be nice to publish a new prototype to the website.

**Comment by Denz1994** [comment]
This issue has been listed for QA to test with specific instructions in https://github.com/phetsims/build-a-molecule/issues/148#issuecomment-611099900.

**Comment by KatieWoe** [comment]
I noticed (using https://github.com/phetsims/QA/issues/506) that, if the molecule is built in a certain way, there may not be room to add some of the atoms needed. Is this acceptable?
Trying to build this in a slightly different configuration:
![cantfinishthis](https://user-images.githubusercontent.com/41024075/84176387-88522300-aa3e-11ea-8eaf-1533849aacc3.png)
No room to add last atoms:
![notfinished](https://user-images.githubusercontent.com/41024075/84176549-cea78200-aa3e-11ea-8ca6-bada913422ec.png)

**Comment by Denz1994** [comment]
Correct me if I'm wrong @arouinfar, but I think the second image in https://github.com/phetsims/build-a-molecule/issues/148#issuecomment-641437201 is technically a different molecule. For instance, the center carbon doesn't have two fluorines bonded to it.

If that is the case then this is acceptable.

**Comment by arouinfar** [comment]
>  I don't think this is necessarily buggy behavior anymore because the user picked a path to build the molecule in a way that makes them run out of space. This is different than having the space to build and the correct atoms and it failing.

Agreed @Denz1994. I think it's important for students to thoughtfully place their atoms when building large molecules. I don't see the current behavior as a bug, but rather a productive constraint.
