### ISSUE TITLE
incorrect nomenclature override

### ISSUE THREAD

**Issue by arouinfar** [phetsims/build-a-molecule#149]
[Ethenone](https://en.wikipedia.org/wiki/Ethenone) is the preferred IUPAC name of C2H2O (arranged H2C=C=O), but is also known as ketene.

Currently, the sim is showing ethenone to be this structure:
![image](https://user-images.githubusercontent.com/8419308/73289454-f72e8e00-41b9-11ea-80f6-6bf92b73b260.png)

This is the correct structure of ethenone, but the nomenclature override is using the less-prefered "ketene".
![image](https://user-images.githubusercontent.com/8419308/73289535-1decc480-41ba-11ea-8e32-ff02276fb930.png)

@Denz1994 can you look into this? The first structure should not be named at all, and the 2nd should be called "ethenone" not "ketene".

**Comment by arouinfar** [comment]
Okay, scratch what I said about the preferred name. Looking at [pubchem](https://pubchem.ncbi.nlm.nih.gov/compound/ketene) (which is what I should have checked first) the preferred name is indeed "ketene". 

@Denz1994 the problem is that this structure is being named, when it isn't actually a molecule that exists.
![image](https://user-images.githubusercontent.com/8419308/73290377-9607ba00-41bb-11ea-8bb9-7f3bfc285686.png)

**Comment by Denz1994** [comment]
Ethenone was removed from the data set so it can't be created. I'm not sure when this data set was generated (the earliest record I could find was 09/6/13 ), but perhaps at that time, this data set was generated ethenone was listed as a molecule in the PubChem database. 

I don't know the standard for how these molecules are named and if they can change over time, but for the time being it has been removed. Does this look good in master @arouinfar?

**Comment by arouinfar** [comment]
Looks good in master @Denz1994. 

H2C=C=O is being named "ketene" which is consistent with the [pubchem entry](https://pubchem.ncbi.nlm.nih.gov/compound/10038), and C-C-O is no longer being given a name.

This issue has also reminded me that we should include some information about nomenclature in the Teacher Tips, but I've created a separate issue for that.
