### ISSUE TITLE
ball and stick representation should show bond order

### ISSUE THREAD

**Issue by arouinfar** [phetsims/build-a-molecule#151]
Noticed during #150. The the ball and stick representation is not showing double or triple bonds. This is a deviation from Java, and is pedagogically problematic. 

Example of a molecule containing a double bond
![image](https://user-images.githubusercontent.com/8419308/73293758-b175c380-41c1-11ea-96d5-2571e05ac048.png)
<img width="602" alt="Screen Shot 2020-01-28 at 11 29 40 AM" src="https://user-images.githubusercontent.com/8419308/73293883-ef72e780-41c1-11ea-9a65-21ebefede34f.png">

Example of molecule containing a triple bond. (Admittedly, this looks pretty gross in Java.) 
![image](https://user-images.githubusercontent.com/8419308/73293812-c8b4b100-41c1-11ea-910f-f7c14d3ac443.png)
![image](https://user-images.githubusercontent.com/8419308/73293836-dc601780-41c1-11ea-93f6-5e0493b68fbb.png)

**Comment by Denz1994** [comment]
Great catch @arouinfar. The bonds were being created according to their bond order. However, they needed to be adjusted so the higher-order bonds would be displaced from a specific offset. What do you think about this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.50/phet/build-a-molecule_all_phet.html)?

Here are some visuals:
Single Bond
![image](https://user-images.githubusercontent.com/13894380/73394614-ed855300-42ab-11ea-950a-d90deb9f1d32.png)

Double Bond
![image](https://user-images.githubusercontent.com/13894380/73394651-ff66f600-42ab-11ea-87b5-d4201217ab70.png)

Triple Bond
![image](https://user-images.githubusercontent.com/13894380/73394675-08f05e00-42ac-11ea-8841-749ae4926c30.png)

**Comment by arouinfar** [comment]
Looks great @Denz1994!
