### ISSUE TITLE
decrease threshold for connecting atoms

### ISSUE THREAD

**Issue by arouinfar** [phetsims/build-a-molecule#154]
Discovered during #113 

The threshold for connecting atoms is currently too large. As a result, it can be a really frustrating experience to cut multiple atoms/pieces off of a molecule.  After severing a bond, clicking elsewhere in the molecule will cause the pieces to rejoin.

![cut](https://user-images.githubusercontent.com/8419308/73404688-515d4b00-42af-11ea-8c29-388d8e7bdcb3.gif)

When severing a bond, the atoms scoot pretty far apart. This distance feels appropriate.
<img src="https://user-images.githubusercontent.com/8419308/73405464-32f84f00-42b1-11ea-9483-a52d2641bf71.png" width=150>

However, the threshold to connect these atoms is (roughly?) the same distance, which causes the reconnection issues in the .gif above. Let's reduce the distance at which the atoms will connect to one another to something more like this:
<img width="87" alt="Screen Shot 2020-01-29 at 4 05 04 PM" src="https://user-images.githubusercontent.com/8419308/73406404-94b9b880-42b3-11ea-992e-f02c4aa682c6.png">

**Comment by Denz1994** [comment]
The bonding and separation thresholds have been reduced to match what is described above. This will need to be reviewed on master @arouinfar.

**Comment by arouinfar** [comment]
@Denz1994 I'm not longer running into issues with parts automatically reconnecting, but the threshold still seems a bit off.

Here are a few gifs showing atoms reaching the threshold distances. In all cases the distance seems quite a bit larger than the last screenshot in https://github.com/phetsims/build-a-molecule/issues/154#issue-557176995. Often, moving an atom/molecule close to another will cause a repulsion and the non-grabbed atom will scoot away from the one that was dropped nearby. This happens regardless of whether a fragment was first cut from a larger molecule, or if freshly connecting atoms from the bucket.
![cut2](https://user-images.githubusercontent.com/8419308/73579726-7e8d3300-4440-11ea-97d7-38a52aba3fdb.gif)
![threshold](https://user-images.githubusercontent.com/8419308/73579907-0ffca500-4441-11ea-9ecf-8ee3148ca0b1.gif)

**Comment by Denz1994** [comment]
This should have been fixed in master in the latest commit. Can you review @arouinfar?

**Comment by arouinfar** [comment]
@Denz1994 I'm not longer seeing the scooting behavior demonstrated in https://github.com/phetsims/build-a-molecule/issues/154#issuecomment-580946345. However, the distance of the threshold still seems quite a bit larger than what was requested. 

![threshold](https://user-images.githubusercontent.com/8419308/74380709-51794280-4da7-11ea-9a4d-b6bcaf9ce7f1.gif)

This is the approximate threshold from the gif above:
![image](https://user-images.githubusercontent.com/8419308/74380392-b1231e00-4da6-11ea-9060-8f3537686d25.png)

Can you reduce the threshold by about half?

**Comment by Denz1994** [comment]
The bonding threshold has been reduced by half. The bonding threshold is essentially the distance from the tolerable distance away from a potential bond position. Reducing this threshold means that users will have to focus on dragging close to the position where the bond is formed (think of the yellow circle's position) and not by just dragging the molecule near the other molecule.

If this is the desired behavior @arouinfar,  then Master should have the above changes and should be reviewed. If not, then we should discuss it further.

**Comment by arouinfar** [comment]
> Reducing this threshold means that users will have to focus on dragging close to the position where the bond is formed (think of the yellow circle's position) and not by just dragging the molecule near the other molecule.

I generally think this is desirable behavior -- users should bring atoms close together when trying to create bonds. Previously, it felt like things were getting sucked together too easily.

@Denz1994 it looks like the scooting/repelling shown in https://github.com/phetsims/build-a-molecule/issues/154#issuecomment-580946345 has been reintroduced. I'm not sure why I can't set two molecules near-ish to each other (still well outside of the threshold) without the repulsion.

**Comment by Denz1994** [comment]
The atoms now repel when the two atoms bonding locations are diagonally aligned. Bromine and Hydrogen are the most extreme case (see 3rd screen, 7th kit) Can you review this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.59/phet/build-a-molecule_all_phet.html) @arouinfar?

**Comment by arouinfar** [comment]
This is looking so much better @Denz1994! I think we can go ahead and close.
