### ISSUE TITLE
Collection box pixel polishing

### ISSUE THREAD

**Issue by arouinfar** [phetsims/build-a-molecule#156]
Design meeting 1/30/20

Pixel polishes
* Move strings above the box
* Add padding between boxes
* Larger collection panel
* Bottom-align ResetAllButton with carousel dots

Self-assigning for mockups

**Comment by arouinfar** [comment]
- [ ] Molecule strings match Collection string -- 16 pt bold (Single screen)
- [ ] 15 px padding between bottom of the black boxes and the molecule string below it. (Single & Multiple)
- [ ] Bottom-align ResetAllButton with carousel dots and right-align with Your Molecules panel (same position on all 3 screens).
![image](https://user-images.githubusercontent.com/8419308/73682807-5ee34e00-467e-11ea-9306-593302ed3d95.png)

**Comment by Denz1994** [comment]
Adjustments have been made as specified above in this [comment](https://github.com/phetsims/build-a-molecule/issues/156#issuecomment-581572455). Can you review this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.55/phet/build-a-molecule_all_phet.html) @arouinfar?

**Comment by arouinfar** [comment]
@Denz1994 this is definitely a nice improvement. A few more minor things:

* It looks like the `ResetAllButton` is still bottom-aligned with the carousel body instead of its dots, so things are currently pretty tight on the Single screen.

* On the Multiple screen, the `You have: {{#}}` string is being obscured a bit by the black box. This is most noticeable when the boxes are empty (bottom of p and y get cut off). 
![image](https://user-images.githubusercontent.com/8419308/73987040-6d3e9d80-48fc-11ea-9fd8-abaa4fbe6f2f.png)

**Comment by Denz1994** [comment]
The above changes have been applied to Master. The bottom of the resetAllButton is aligned with the bottom of the page control buttons (not the top). Also, there was a spacing added to the `CollectionBoxNode` VBox options so the box's edge doesn't overlap its label text.

Could you review @arouinfar?

**Comment by arouinfar** [comment]
Looks good @Denz1994, thanks!
