### ISSUE TITLE
Collection box names and goals should be placed above the boxes

### ISSUE THREAD

**Issue by Denz1994** [phetsims/build-a-molecule#157]
From design meeting on 01/31/20:

The design team agreed the labeling of the boxes should be located above the box. This is consistent with the java version.

**Comment by Denz1994** [comment]
Labels have been adjusted. Can you make sure this looks okay in this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.52/phet/build-a-molecule_all_phet.html) @arouinfar?

**Comment by arouinfar** [comment]
Looks good @Denz1994. Further pixel polishing of the collection panel will be handled in #156.
