### ISSUE TITLE
Screen Bug on IPad when page is refreshed

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/build-a-molecule#160]
**Test device**
IPad 6th generation
**Operating System**
IOS 13
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/QA/issues/479

The molecules represented on the various screens (in the home screen or on the bar at the bottom) seem to be misplaced. Occurs on page refresh usually.
**Steps to reproduce**
1. Open Build a Molecule
2. Refresh the page
**Visuals**
![2020-02-14BldMlclScrnBg](https://user-images.githubusercontent.com/54685448/74564279-f15fd900-4f2b-11ea-8152-74319fb7dbc5.jpg)

**Comment by Denz1994** [comment]
An icon factory has been introduced to manage the homescreen/nav-bar icons. Also, there were some options added to `Image( {initialWidth, initialHeight})`. Can you try this out on an IPad @loganbraywork?

**Comment by KatieWoe** [comment]
Looks good
