### ISSUE TITLE
Atoms fail to separate properly from molecules using touch

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/build-a-molecule#161]
**Test device**
IPad 6th generation
**Operating System**
IOS 13
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/QA/issues/479

When using touch to separate atoms, it does not always work and sometimes simply creates gaps in the molecule.
**Steps to reproduce**
1. Create a molecule
2. Attempt to separate the atoms of the molecule by using touch on the yellow dot
**Visuals**

![2020-02-14BldMlcSprtGIF](https://user-images.githubusercontent.com/54685448/74566096-ec048d80-4f2f-11ea-8ff4-4b8f45ef8e0a.gif)

**Comment by Denz1994** [comment]
The atomNodes were getting hit by touch snag events after clicking the bond targets. The touch snag has been removed and the atoms can be separated now. Will release a dev version for verification.

**Comment by Denz1994** [comment]
Can you confirm this was fixed in this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.59/phet/build-a-molecule_all_phet.html) @loganbraywork?

**Comment by loganbraywork** [comment]
Assigning @KatieWoe  as well as I currently have no access to an IPad

**Comment by KatieWoe** [comment]
Was not able to reproduce the issue in the above dev version

**Comment by Denz1994** [comment]
Thanks for testing. I'll close this one.
