### ISSUE TITLE
Multitouch interaction with collections allows for movement of atom outside of boundry

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/build-a-molecule#162]
**Test device**
IPad 6th generation
**Operating System**
IOS 13
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/QA/issues/479

If an atom is held  and the collection is changed using multitouch, then when returning to the inital collection it is still possible to manipulate atom outside of bounderies
**Steps to reproduce**
1. Complete at least 1 collection
2. Lift up an atom using one finger
3. Without releasing the atom, use multitouch to switch collections
4. Switch collections back to initial while continuing to hold atom
5. Drag atom towards buckets and observe
**Visuals**
![2020-02-14BldMlcMltiTchGltch](https://user-images.githubusercontent.com/54685448/74567460-160b7f00-4f33-11ea-8000-24a79aed84dd.gif)

**Comment by Denz1994** [comment]
The drag events for other atoms are now interrupted while dragging or interacting with other touch events. Will release dev version for comparison.

**Comment by Denz1994** [comment]
The interrupt also occurs when the collections are swapped.

**Comment by loganbraywork** [comment]
Also assigning @KatieWoe due to having no access to an IPad currently due to the coronavirus pandemic

**Comment by KatieWoe** [comment]
Seems fixed in that dev version
