### ISSUE TITLE
StringTest Long causes collection box and atom box to overlap

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/build-a-molecule#164]
**Test device**
Windows 10 laptop & Lovelace
**Operating System**
ChromeOS and Windows 10
**Browser**
Chrome
**Problem description**

For https://github.com/phetsims/QA/issues/479

The long stringtest query parameter causes the collection box and atom box to overlap

**Steps to reproduce**

1. Add ?stringTest=long query parameter
2. Enter the Single screen

**Visuals**
![2020-03-06BLDMCL](https://user-images.githubusercontent.com/54685448/76120569-ff46ce00-5fae-11ea-82b3-1b3b01adfd23.png)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Molecule‬
URL: https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.58/phet/build-a-molecule_all_phet.html
Version: 0.0.0-dev.58 2020-02-12 22:53:42 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
Language: en-US
Window: 1604x792
Pixel Ratio: 1.1979166269302368/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON:

**Comment by Denz1994** [comment]
Max widths were adjusted to the `CollectionPanel` texts. I will release a new dev version for verification.

**Comment by Denz1994** [comment]
This should be fixed in this dev [version](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.61/phet/build-a-molecule_all_phet.html) @loganbraywork. Can you verify?

**Comment by loganbraywork** [comment]
Appears to be fixed!
