### ISSUE TITLE
IE, only secure content shown.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#165]
**Test device**
Dell

**Operating System**
Win 10

**Browser**
IE

**Problem description**
For https://github.com/phetsims/QA/issues/479
Some visuals seem to be blocked in IE. When the cursor is meant to turn into scissors, it disappears instead. If you give IE permission it will reload and show it then.

**Visuals**
![securecontent](https://user-images.githubusercontent.com/41024075/76265082-36c0af00-6229-11ea-9607-fef535993b58.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
  
Name: ‪Build a Molecule‬

URL: https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.58/phet/build-a-molecule_all_phet.html

Version: 0.0.0-dev.58 2020-02-12 22:53:42 UTC

Features missing: touch, fullscreen

Flags: pointerEnabled, msPointerEnabled, pixelRatioScaling

User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0; rv:11.0) like Gecko

Language: en-US

Window: 1536x750

Pixel Ratio: 2.5/1

WebGL: WebGL 0.94

GLSL: WebGL GLSL ES 0.94

Vendor: Microsoft (Internet Explorer)

Vertex: attribs: 16 varying: 15 uniform: 512

Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)

Max viewport: 16384x16384

OES_texture_float: true

Dependencies JSON: {}

</details>

**Comment by Denz1994** [comment]
The cursor on IE and Edge has been adjusted to its default pointer because it violates the default browser security settings. Can you try this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.65/phet/build-a-molecule_en_phet.html) @arouinfar on Edge or IE? Is using the default pointer a satisfactory fallback on these browsers or should we look for another solution?

**Comment by KatieWoe** [comment]
@Denz1994 not Edge I believe. Just IE

**Comment by Denz1994** [comment]
Good catch. This [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.66/phet/build-a-molecule_en_phet.html) should only affect IE.

**Comment by arouinfar** [comment]
Since this is an IE-only issue, and IE is a low-use platform, I believe this is probably acceptable. The warning message looks a bit scary, though, so I'd like @ariel-phet to weigh in here.

**Comment by ariel-phet** [comment]
@Denz1994 - can the default pointer be used by "default" when on IE so we never get this warning? I believe we have IE detection in multiple sims.

**Comment by Denz1994** [comment]
@KatieWoe Can you confirm on IE that the pointer doesn't change to a scissor icon when the cursor is positioned over the yellow bond target? The cursor should look like its hovering over an interactable object with a hand icon.

The dev version can be found [here](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.67/phet/build-a-molecule_en_phet.html).

**Comment by KatieWoe** [comment]
This looks fixed on IE

**Comment by Denz1994** [comment]
Thanks for checking closing this one.
