### ISSUE TITLE
follow naming convention for Enumerations

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/build-a-molecule#166]
From https://github.com/phetsims/phet-core/issues/43...

In Direction.js, rename `DIRECTION` to `Direction`.

In Molecule3DDialog.js, rename `VIEW_STYLE` to `ViewStyle`

**Comment by Denz1994** [comment]
The casing was corrected for `DIRECTION` to `Direction` and `VIEW_STYLE` to `ViewStyle`. Closing this one.
