### ISSUE TITLE
Delete temp production deploy

### ISSUE THREAD

**Issue by mattpen** [phetsims/build-a-molecule#167]
Per request from @kathy-phet, there was a temporary dev version deployed to the production location. This must be removed from phet-server before version 1.0 is deployed with the build server.

It can be removed by running the following on phet-server:

`rm -rf /data/web/static/phetsims/sims/html/build-a-molecule`

Contact me if there are any questions.

**Comment by Denz1994** [comment]
Make sure to run the above command BEFORE `grunt production`.  In between running the rm command above and making the sim visible on the website, the sim won't be available.

**Comment by Denz1994** [comment]
The prototype was removed from phet-server and the sim has been published. Closing this issue.
