### ISSUE TITLE
Add Proper Credits

### ISSUE THREAD

**Issue by Denz1994** [phetsims/build-a-molecule#168]
This issue is being opened to track changes to credits for 1.0.0 publication.

Currently, the credits are as follows:
```
  credits: {
    leadDesign: 'Amy Rouinfar',
    softwareDevelopment: 'Denzell Barnett, Johnathan Olson',
    team: 'Ariel Paul, Kathy Perkins',
    qualityAssurance: 'Ethan Johnson, Liam Mulhall, Benjamin Roberts, Jacob Romero,Kathryn Woessner'
  }
```

@arouinfar and @KatieWoe are there any others that should be added?

**Comment by KatieWoe** [comment]
Logan Bray has done a fairly large amount on it. There also isn't a space between Jacob's name and mine

**Comment by arouinfar** [comment]
@Denz1994 I added the legacy design team to the credits and addressed https://github.com/phetsims/build-a-molecule/issues/168#issuecomment-604110007 in the above commit.

Back to @Denz1994 to decide whether or not to keep this issue open for finalizing QA credits once we're in rc or open a new issue when the time comes.

**Comment by Denz1994** [comment]
I'll keep this issue open to finalize during RC.

**Comment by Denz1994** [comment]
Should be verified once more in the latest RC.

**Comment by KatieWoe** [comment]
Jaspe Arias and Steele Dalton should be added as well for rc.2

**Comment by Denz1994** [comment]
Credits have been updated.

**Comment by Denz1994** [comment]
Closing this one.

**Comment by KatieWoe** [comment]
@arouinfar should you be added too?

**Comment by arouinfar** [comment]
Thanks for checking @KatieWoe, but I'm already credited.
