### ISSUE TITLE
Zoom out a bit in 3D dialog

### ISSUE THREAD

**Issue by arouinfar** [phetsims/build-a-molecule#169]
Discovered in #148 

If a molecule is very large, it may not fit inside the viewing window of the 3D dialog, regardless of the representation (space filling or ball-and-stick). For example:
![image](https://user-images.githubusercontent.com/8419308/77958375-2fbe1700-7292-11ea-9b1d-c2164237aa36.png)

@Denz1994 can you zoom the view out a bit? This would be a universal adjustment, not just for large molecules.

**Comment by Denz1994** [comment]
Can you check out the zoom distance on master @arouinfar? The camera should be zoomed out to capture more of the molecule.

**Comment by arouinfar** [comment]
The zoom level in master is looking good. Thanks @Denz1994.
![image](https://user-images.githubusercontent.com/8419308/77967995-82ec9580-72a3-11ea-94aa-a459467c24ba.png)
![image](https://user-images.githubusercontent.com/8419308/77968004-8849e000-72a3-11ea-8ab5-c81f8b4a5ffb.png)
