### ISSUE TITLE
User suggestion: collection design, ions

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/build-a-molecule#175]
> First reactions as a user on the "Build a Molecule" sim:
> • This is a crucial tool for students, and I didn't even realize that I needed it!
> • I love the "Collection" idea - it feels like I'm earning things in a video game. I even felt kind of annoyed when the sim asked me to make another H2O when I'd made it already. It feels like I should be able to pull out the H2O whenever I want (in one session), including in the playground after I've built it once.
> • I love that the system will give you the name of a molecule when you build it correctly. I wonder what clues students might have for figuring out what arrangements are valid. Valence info, maybe?
> 
> • DPS and CU Boulder are developing a unit on ocean acidification that I'm a part of piloting. Students are asked to figure out how CO2 and H2O creates H3O+ ions. A couple things came up while testing how we might use the playground to accomplish this:
> 
>   - Is it possible to allow the building of ions? H3O+ currently doesn't exist, which makes this acidification activity hard to do...
>   - Is there a reason why we only get to use limited copies of each atom to build with? I'd love to create a "particle equation", showing both reactants and products, but I don't  have enough atoms.
>   - Thinking pie in the sky, it could be very cool to have a "equation playground" tab that actually tallied atoms before and after the reaction to determine if the equation is balanced.

**Comment by arouinfar** [comment]
> Is it possible to allow the building of ions? H3O+ currently doesn't exist, which makes this acidification activity hard to do...

No. Our database of molecules is a subset of the data in PubChem. Currently, it does not include ions, only neutral molecules. If we wanted to add ions, it would add 1000's of new entries, and students would often encounter named ions while building their atoms. This would be distracting, and does not serve this sim's learning goals.

> Is there a reason why we only get to use limited copies of each atom to build with? I'd love to create a "particle equation", showing both reactants and products, but I don't have enough atoms.

Yes, even with the limitations currently in place, the database of possible molecules is quite large. It currently contains ~9000 possible molecules.

>Thinking pie in the sky, it could be very cool to have a "equation playground" tab that actually tallied atoms before and after the reaction to determine if the equation is balanced.

This goal is better served by the Balancing Chemical Equations sim (and possibly RPAL too). @oliver-phet can you please the links to these sims with the user?

**Comment by oliver-phet** [comment]
Thanks Amy, email to user sent!
