### ISSUE TITLE
Bucket input handling

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/build-a-molecule#176]
It seems like an improvement to do what we've done in some other sims, where you can grab an atom by pressing on the bucket itself (which will grab an atom from the bucket), not just grabbing individual atoms. Right now it takes a lot more effort to grab an individual atom.

**Comment by Denz1994** [comment]
This feature has been added in the commit above. Clicking on the bucket will grab the closest atom within the bucket. The new behavior is a nice addition. Tagging @arouinfar for any other input.

**Comment by arouinfar** [comment]
@Denz1994 this is a really nice feature. I like it!
