### ISSUE TITLE
Pointer area review

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/build-a-molecule#177]
As noted in the code review doc (https://github.com/phetsims/build-a-molecule/issues/173), there should be a review of pointer areas done and signed off.

**Comment by Denz1994** [comment]
Note: Pointer areas are shown for buckets that aren't yet visible but exist in the carousel's preceding and succeeding pages.

Assigning to @arouinfar to sign off on pointer areas.

**Comment by arouinfar** [comment]
The pointerAreas look sufficiently dilated to me, but I don't have a touch device to test it on. @Denz1994 if this sim has already been tested on an iPad, I think it's safe to assume the touch areas are fine as-is.

**Comment by Denz1994** [comment]
This sim has been tested on an iPad and the only issues that came up regarding touch areas were https://github.com/phetsims/build-a-molecule/issues/116. This issue is safe to close.
