### ISSUE TITLE
i18n of molecule names

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/build-a-molecule#178]
Just want to check in and see if we were planning on allowing translation of molecule names at all (came up in https://github.com/phetsims/build-a-molecule/issues/173).

**Comment by arouinfar** [comment]
I think it would be nice to allow for i18n of the names of the 26 molecules in [collectionMoleculesData.js](https://github.com/phetsims/build-a-molecule/blob/master/js/common/model/data/collectionMoleculesData.js). It would be overkill (and not particularly useful) to allow i18n of the names of the 9000+ molecules in otherMoleculesData.js.

**Comment by Denz1994** [comment]
The 26 molecules in collectionMoleulesData.js are responsible for the molecules that show in the collection box. These strings are translatable as indicated by the `stringTest` query parameter. There are no further actions for this issue. Closing this issue.

**Comment by jbphet** [comment]
@DianaTavares contacted me via Slack and said that she was unable to translate the molecule names used in this sim into Spanish through the translation utility (aka Rosetta).  I just logged into Rosetta and brought up the page for build-a-molecule and Spanish, and indeed, the molecule names from `collectionMoleculesData.js` are not available for translation.  Above, @arouinfar recommended that they should be.

@Denz1994 - I think your test for translatability may have been flawed.  I don't think testing that a string can be altered via `stringTest` proves that it is translatable.  Can you investigate further?  I think there may need to be some sort of mapping of the molecule names in `collectionMoleculesData.js` to strings in `build-a-molecule-strings_en.json`.

Also assigning @ariel-phet for prioritization.

**Comment by ariel-phet** [comment]
@Denz1994 this would probably be good to fix when we add in the new molecule data

**Comment by oliver-phet** [comment]
Just to add, please let me know when this has been added so that I can inform translators. I just got a report about this from Sandor.

**Comment by jbphet** [comment]
@Denz1994 and I discussed this today and he has a rough plan for how to make the molecules translatable.  I offered to help with testing of the changes, since it will involve making changes to babel that we want to make sure don't get committed, at least not to the master branch.

**Comment by Denz1994** [comment]
The strings that were previously used in the collection boxes were pulled from the `CollectionMoleculesData.js` and parsed for the molecule name. These didn't come from the string.json file. Some internal support was implemented  so these "unofficial" strings could be changed under the testing conditions fired from the `stringTest=` query parameter. 

The revision here was to add the entries for each file and then change `CompleteMolecule.getDisplayName()` to utilize the string from the .json file. If the molecule doesn't have an entry, it fallsback to using English (recovered from `CollectionMoleculeData.js`).

These entires were tested with the URL: http://localhost:8080/build-a-molecule/build-a-molecule_en.html?brand=phet&ea&easyMode&locale=es and a truncated `build-a-molecule-strings_es.json` file was built in babel (under the `tests` branch, **not checked in**).

This produced the below snapshot where the collection box, common name in dialog, and common name above the built molecule are all translated. Water, molecular oxygen, and molecular hydrogen were tested.

![image](https://user-images.githubusercontent.com/13894380/98059546-66a26f80-1e15-11eb-9a8a-f3bae07ed927.png)

**Comment by Denz1994** [comment]
Assigning to @jbphet for review. I believe this should have fixed the issue.

**Comment by Denz1994** [comment]
While reviewing with @jbphet, we thought the implementation detailed above works as expected. These additional strings were tested against currently published "es" strings. @jbphet suggested doing a maintenance release and checking for these strings in the HTML of the built RC. Search for `BUILD_A_MOLECULE/water` for example.

**Comment by Denz1994** [comment]
During the build process unused strings are stripped from the build artifact. When the strings are accessed via bracket notation (i.e. `buildAMoleculeStrings[acetylene]`), they don't get registered as accessed strings like when dot notation is used (i.e. `buildAMoleculeStrings.acetylene`).

We don't know what the strings are prior to loading the sim data so, we need to access them via a pseudo Strings object within `CompleteMolecule.js`. These additional strings are found in the HTML of the lastest [RC build](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.1-rc.1/phet/build-a-molecule_all_phet.html), so they can be translated once this version is pushed to production.

**Comment by Denz1994** [comment]
Changes have been pushed. I'd suggest @DianaTavares try to translate one of the molecules in the collection boxes like "water" for example.

**Comment by arouinfar** [comment]
@Denz1994 two of the English strings are formatted like the string key, which is odd.
![image](https://user-images.githubusercontent.com/8419308/98247712-3b14a780-1f31-11eb-8b98-43a5ddb6d7da.png)

Compare to other two-word molecule names:
![image](https://user-images.githubusercontent.com/8419308/98247781-4bc51d80-1f31-11eb-9cea-8dcda64201e1.png)

Unfortunately, this means that the molecule names of CO and CO2 appear incorrectly in the English sim.
![image](https://user-images.githubusercontent.com/8419308/98248184-d4dc5480-1f31-11eb-974e-99993af16c07.png)

**Comment by DianaTavares** [comment]
the translations are working pretty well:

![image](https://user-images.githubusercontent.com/26031501/98275100-e0dc0c80-1f59-11eb-884b-a64fca307965.png)

And now I have a long list of molecules names to translate in the translation tool.

But @arouinfar is right, the English names are strange:
![image](https://user-images.githubusercontent.com/26031501/98275247-1254d800-1f5a-11eb-9b50-c59485332003.png)

**Comment by Denz1994** [comment]
Correct, the English entry didn't have a space for the two strings mentioned above. I'd just like an additional look at this change. In this version the two strings have been fixed. Can you confirm @arouinfar?

https://phet-dev.colorado.edu/html/build-a-molecule/1.0.2-rc.1/phet/build-a-molecule_all_phet.html

**Comment by ariel-phet** [comment]
@Denz1994 I verified this fix

**Comment by Denz1994** [comment]
Strings have been deployed [here](https://phet.colorado.edu/sims/html/build-a-molecule/latest/build-a-molecule_en.html). Closing.
