### ISSUE TITLE
Common prefix name for source files

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/build-a-molecule#180]
From the code review in https://github.com/phetsims/build-a-molecule/issues/173:

> Do filenames use an appropriate prefix? Some filenames may be prefixed with the repository name, e.g. MolarityConstants.js in molarity. If the repository name is long, the developer may choose to abbreviate the repository name, e.g. EEConstants.js in expression-exchange. If the abbreviation is already used by another respository, then the full name must be used. For example, if the "EE" abbreviation is already used by expression-exchange, then it should not be used in equality-explorer. Whichever convention is used, it should be used consistently within a repository - don't mix abbreviations and full names.

It looks like BAM is the prefix, but we have BuildAMoleculeQueryParameters... can we rename that to be consistent?

**Comment by Denz1994** [comment]
The filename has been changed along with its usages. Closing this issue.
