### ISSUE TITLE
Implementation details in model.md documentation

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/build-a-molecule#183]
As noted in the code review doc (https://github.com/phetsims/build-a-molecule/issues/173):

> Does model.md adequately describe the model, in terms appropriate for teachers?

Can we move implementation details to the implementation-notes.md?

**Comment by Denz1994** [comment]
Implementation notes and the model.md have both been updated. The model.md is geared towards an audience of teachers, while the implementation notes are written for devs.

Closing this one.
