### ISSUE TITLE
Right clicking on buckets puts atoms in the play area

### ISSUE THREAD

**Issue by muedli** [phetsims/build-a-molecule#186]
<b>Test Device</b>

MacBook Air

<b>Operating System</b>

macOS 10.15.4

<b>Browser</b>

Google Chrome 81.0.4044.138

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/506. Not a big issue, and you might decide to close it right away. I just wanted to bring it up in case you or @arouinfar don't like the behavior or think it's problematic in some way.

Anyway, if you right click on a bucket, an atom will sort of shoot into the play area.

<b>Visuals</b>

![issue](https://user-images.githubusercontent.com/60749003/83570787-e5505500-a4e3-11ea-8e56-ee89cec406fe.gif)

<details>
<summary><b>Troubleshooting Information</b></summary>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Molecule‬
URL: https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.75/phet/build-a-molecule_all_phet.html
Version: 1.0.0-dev.75 2020-06-01 13:20:12 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Language: en-US
Window: 1440x821
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by Denz1994** [comment]
I don't think this is problematic but @ariel-phet may have some further input. Reassigning.

**Comment by ariel-phet** [comment]
Although this behavior is not ideal, it does not really cause any pedagogically problematic issues.

I think most people would realize fairly soon that they are right clicking and avoid it. Fixing this issue would likely be much more effort than worth. 

Closing as `wontfix`
