### ISSUE TITLE
Long strings slightly covered up in collections

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/build-a-molecule#188]
**Test device**

Windows 10 Laptop

**Operating System**

Windows 10 v.1903

**Browser**

Edge Version 83.0.478.44 (Official build) (64-bit)

**Problem description**

For https://github.com/phetsims/QA/issues/506

The long strings are slightly covered up in collection view.

**Visuals**

![2020-06-05BldBlclLngStringtest](https://user-images.githubusercontent.com/54685448/83924993-475ac580-a743-11ea-8b83-ad38ed6d7488.PNG)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.75/phet/build-a-molecule_all_phet.html?stringTest=long
Version: 1.0.0-dev.75 2020-06-01 13:20:12 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36 Edg/83.0.478.44
Language: en-US
Window: 1313x647
Pixel Ratio: 1.4625000953674316/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by Denz1994** [comment]
Some vertical spacing was added between the black box highlight and the goal text. There isn't much space to work with but there shouldn't be an overlap anymore.

I'll release a dev version for verification.

**Comment by Denz1994** [comment]
This [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.76/phet/build-a-molecule_all_phet.html) can be used for verification.

**Comment by KatieWoe** [comment]
Noticed some overlap when strings were normal, so I took a second look at dev.76 and it looks better there, but I did notice a very, very small amount of overlap. @Denz1994 feel free to close again if you don't think this needs to be addressed. Not sure myself.
![moreoverlap76](https://user-images.githubusercontent.com/41024075/84425146-54adff00-abde-11ea-9668-6876de571f24.png)
![overlapindev76](https://user-images.githubusercontent.com/41024075/84425148-55469580-abde-11ea-9a16-772c1fd5d800.png)

**Comment by Denz1994** [comment]
I've given as much room to the strings as possible without compromising the positioning of the resetAllButton. The collection panel will encroach on the upper bounds on the button if we add more spacing. I'll close for now since the button positioning takes a higher priority than the very very small overlap mentioned above.
