### ISSUE TITLE
Radii / locations for molecules

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/build-a-molecule#19]
See CCl3, BF3, other examples. BF3 is where the hydrogen 'spheres' are entirely inside of the boron. CCl3 shows a more complicated intersection example.

Do we need differences for Van der Waals / covalent / ionic? Jmol may be handling these for us?

**Comment by Denz1994** [comment]
@ariel-phet this issue has been lingering for a while. Can you either address this issue or refer to @jonathanolson for more information?

**Comment by ariel-phet** [comment]
Looking at the current version, things seem to be looking pretty good, but we should consult with @jonathanolson at design meeting to see if it can be closed.

**Comment by Denz1994** [comment]
I found in the Jmol [docs](http://jmol.sourceforge.net/docs/) the various radii used for each element [here](http://jmol.sourceforge.net/docs/). I think we only ran into problems described in https://github.com/phetsims/build-a-molecule/issues/111#issuecomment-577371906.

**Comment by Denz1994** [comment]
As discussed at the design meeting on 01/30/20:

> Do we need differences for Van der Waals / covalent / ionic?

We shouldn't do anything different than what was done in the java version. The Java version is working and users haven't complained. Closing this one.
