### ISSUE TITLE
503 Backend Fetch

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#195]
For https://github.com/phetsims/QA/issues/506. When looking at the console (Win 10 Chrome) on both the sim and the debug sim, there seems to be an error that occurs during loading. I haven't seen any issues that I can relate to this while playing with the sim itself.
![notsureerror](https://user-images.githubusercontent.com/41024075/84208245-81dc9f00-aa70-11ea-8432-fa999285956a.png)

**Comment by Denz1994** [comment]
I'm not sure what this is related to and I can't reproduce consistently, despite seeing this message before. I'll ask other devs if they have any insight.

**Comment by Denz1994** [comment]
In regards to the reproducibility of this error, I can only replicate this in a dev version.

**Comment by Denz1994** [comment]
I'm not sure what the origin of this issue is, but it isn't sim specific. I'll label this issue as "won't-fix" and when I get more information address this in a separate issue if it warrants a fix.

**Comment by pixelzoom** [comment]
I see a similar 404 error all the time when running sims locally from my working copy.  I have not seen this 403 error when running from phet-dev, and I cannot reproduce.  and I'm not sure why it would be a 403 error.   If you're unfamiliar with favicon.icon, see https://en.wikipedia.org/wiki/Favicon.  A favicon.icon for a non-production version is probably safe to ignore.
