### ISSUE TITLE
Full crash when building a large molecule

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#197]
**Test device**
Dell and Lovelace
**Operating System**
Win 10 and ChromeOS
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/506.
When building a particular large molecule the sim crashed as I added the last hydrogen. I have not seen this with any other molecule, and no error happened in the console. This means I'm unsure if this occurs with other molecules. I will add any others that this occurs in. When the bug occurs the sim freezes. Refreshing the page doesn't even seem to work, the tab must be exited entirely.
**Steps to reproduce**
1. Go to the third screen
2. Go to the 6th page of the carousel so you can use Phosphorus, Carbon, and Hydrogen.
3. Put a Phosphorus in the play area and attach four Carbon to it.
4. Start adding Hydrogen to the Carbons.
5. When you reach 11 Hydrogen, a molecule name will appear. If you attempt to add a 12th, the sim crashes

**Visuals**
![fullcrashlargemolecule](https://user-images.githubusercontent.com/41024075/84528182-6d7cea00-ac9c-11ea-8337-f83a9cf9bdcb.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Molecule‬
URL: https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.75/phet/build-a-molecule_all_phet.html
Version: 1.0.0-dev.75 2020-06-01 13:20:12 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
Happens with a nitrogen in the center, 4 carbon, and 7 hydrogen as you try to add the 8th.

**Comment by Denz1994** [comment]
I believe there was a runtime error in MoleculesStructure.checkEquivalencyMatrix(). We were targetting the incorrect index for the submatrices to be removed. This should have been corrected in this dev version. Can you test it out [here](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.78/phet/build-a-molecule_all_phet.html) @KatieWoe?

**Comment by KatieWoe** [comment]
This looks fixed in the two instances I saw. I'll keep an eye out for any others, but the two I did find seem good.

**Comment by Denz1994** [comment]
Good to know. I'll make sure to include this for further inspection in the next RC. Closing this one for now.
