### ISSUE TITLE
Multitouch still dragging molecule when looking at different part of carousel

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#199]
**Device**
iPad
**OS**
iPadOS 13
**Browser**
Safari
Problem Description
For https://github.com/phetsims/QA/issues/506. 
If you are dragging a molecule with one finger and use the other to change the carousel to another page, you will still be dragging an invisible molecule. You can even drop it into the answer box like this. May not be worth addressing.
**Steps**
1. Go to first screen
2. Build a target molecule
3. Using touch, start dragging the molecule and don't let go
4. With another finger, hit one of the buttons to move to another carousel page
5. Drag your finger to the answer box and let go

**Visuals**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/41024075/84552164-16433d80-accd-11ea-9b00-1e9646f75d4a.gif)

**Comment by Denz1994** [comment]
Good catch. We can kill the dragging input when the carousel pages change. Should be fixed in this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.78/phet/build-a-molecule_all_phet.html) @KatieWoe.

**Comment by KatieWoe** [comment]
Looks good in the dev version

**Comment by Denz1994** [comment]
Nice. Closing this one.
