### ISSUE TITLE
PropertyStateHandler dependency registration leaks memory

### ISSUE THREAD

**Issue by zepumph** [phetsims/build-a-molecule#205]
A memory leak was outlined and fixed in master over in https://github.com/phetsims/axon/issues/328#issuecomment-681042541. It effects PhET brand. Please follow that link to cherry-pick changes into the next maintenance release of this sim.

**Comment by samreid** [comment]
On hold until https://github.com/phetsims/axon/issues/328#issuecomment-681071910 is cleared up.

**Comment by Denz1994** [comment]
Based on @samreid investigation in https://github.com/phetsims/axon/issues/328#issuecomment-681174532 and https://github.com/phetsims/axon/issues/328#issuecomment-681357413 it looks like this sim wasn't affected by a memory leak and a patch isn't essential.

These RC shas also underwent a check for memory leaks in the first RC and no leaks were found. https://github.com/phetsims/QA/issues/509#issuecomment-674233559. This was also after a preceding dev test where there wasn't much time in between test cycles. That dev-test recorded no memory leaks as well.

Closing this issue. If there are any memory leaks found during testing of the next maintenance release, I'll reopen this issue and investigate if the leaks are related to this.
