### ISSUE TITLE
Possible Misordering of Chemical Formula

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#206]
For https://github.com/phetsims/QA/issues/538
From Slack:

>Kathryn Woessner:house_with_garden:  2:12 PM
Should both of these molecules be CHN, even though they are put together differently?

![chnforboth](https://user-images.githubusercontent.com/41024075/91352495-2be1e280-e7a7-11ea-8751-8e1bdb345b4c.gif)

>Amy Rouinfar  2:13 PM
Hydrogen cyanide is usually HCN .
2:14
The order in the chemical formula doesn’t technically matter, though. (edited) 

>Kathryn Woessner:house_with_garden:  2:14 PM
It's that way in the game too

![thatingame](https://user-images.githubusercontent.com/41024075/91352552-3b612b80-e7a7-11ea-8751-49d78de028af.png)

>2:14
Is it worth an issue?

>Amy Rouinfar  2:14 PM
Yes
2:15
I saw something similar in the collections but it wasn’t as glaring…
2:16
Looks like I don’t still have it up, so I’ll have to find it again. But it was something unconventional like O2C for carbon dioxide instead of the usual CO2 .

>Denzell Barnett  2:17 PM
Pub chem says the formula is HCN or CHN. What would be the ideal fix?

>Amy Rouinfar  2:17 PM
HCN would be ideal
New
2:18
CHN is probably following a common ordering convention for larger organic molecules, but HCN implies the atoms are connected H-C-N which is preferable here.

**Comment by Denz1994** [comment]
Also from the same slack thread:

> Amy Rouinfar  4:23 PM
> H-C-N and C-N-H are both legal structures. C-H-N is not a legal structure.
> 4:23
> We should change the goal text for hydrogen cyanide to HCN.

**Comment by arouinfar** [comment]
@Denz1994 if it is trivial to change the chemical formulas in [collectionMoleculesData.js](https://github.com/phetsims/build-a-molecule/blob/master/js/common/model/data/collectionMoleculesData.js), I'd also like to make these changes:

- [ ] ammonia|H3N  --> NH3
- [ ] phosphine|H3P --> PH3
- [ ] silane|H4Si --> SiH4
- [ ] sulfur dioxide|O2S --> SO2

**Comment by KatieWoe** [comment]
I'm a bit confused since I think at least some of those are already right? I think I just saw silane come up and it was right.

**Comment by KatieWoe** [comment]
Ammonia is wrong though. So maybe I saw silane wrong

**Comment by arouinfar** [comment]
I was assuming that the chemical formula that appears in the collection came directly from collectionMoleculesData.js. I am pretty sure I saw `H3N` and `O2S` earlier today. I'll play with the collections a bit more to make sure.

**Comment by KatieWoe** [comment]
Looks like an odd mixed bag:
![mixed bag](https://user-images.githubusercontent.com/41024075/91354939-ae1fd600-e7aa-11ea-97c8-585aa27be636.png)

**Comment by Denz1994** [comment]
Because these entries come directly from the PubChem database, we would need to review the entries or develop a post-processing step to follow a heuristic for editing the formula names. It seems like PubChem doesn't follow a pattern. It would be reasonable to at the least check the collection box goal molecules. 

These are found in collectionMoleculesData.txt mentioned above.

**Comment by arouinfar** [comment]
Of the five molecules that have an odd chemical formula ordering in collectionMoleculesData.js, three of them appear to be use the more preferable chemical formula ordering in the collection:

![image](https://user-images.githubusercontent.com/8419308/91354888-99434280-e7aa-11ea-8f4b-3a933e93c184.png)
![image](https://user-images.githubusercontent.com/8419308/91355459-68afd880-e7ab-11ea-85e1-f6b3f2502153.png)
![image](https://user-images.githubusercontent.com/8419308/91355623-a7459300-e7ab-11ea-8c19-83471ca389d4.png)


These two molecules use the exact chemical formula ordering in otherMoleculesData.js, and I think the ordering is less than ideal.
![image](https://user-images.githubusercontent.com/8419308/91355099-ed4e2700-e7aa-11ea-86cd-ad04b9309f92.png)
![image](https://user-images.githubusercontent.com/8419308/91356383-cee92b00-e7ac-11ea-8fc3-d3456ed33f31.png)

**Comment by KatieWoe** [comment]
Other chemicals that are more complicated seem impacted as well:
![h4n2](https://user-images.githubusercontent.com/41024075/91357020-ce04c900-e7ad-11ea-8adf-ad532af85b73.png)

**Comment by KatieWoe** [comment]
Wikipedia says the above should be N2H4

**Comment by KatieWoe** [comment]
Not sure of this one, so posting just in case:
![couldnttellpho](https://user-images.githubusercontent.com/41024075/91358148-8d0db400-e7af-11ea-9e32-25cc0f3c1bbf.png)

**Comment by arouinfar** [comment]
I don't think there's anything we can or should do about molecular formulas in otherMoleculesData.js. [PubChem](https://pubchem.ncbi.nlm.nih.gov/compound/9321) lists H4N2 as an acceptable formula for Hydrazine. I think PubChem is using a convention where the formula is ordered C > H > N > O.

To be clear, the formulas for hydrogen cyanide and ammonia are not wrong when ordered this way, but they just look weird. I think `HCN` and `NH3` are going to be more familiar to students, which is why it'd be nice if the formulas could show up that way in the collections. @Denz1994 is that possible?

**Comment by Denz1994** [comment]
@arouinfar We have an internal function used to get the formula of molecules this is in `MoleculeStructure.getGeneralFormula`.

More specifically here are some comments from the code:
```
   // carbon first, then hydrogen, then others alphabetically, otherwise sort by increasing electronegativity
```
This relates to the order of elements in the formula.  Also here are some exception cases for H3N and CHN below.
```
'H3N': 'NH3', // treated as if it is organic
'CHN': 'HCN'  // not considered organic
```

I'll continue with the suggested changes you posted above, but I wanted to leave this here in case it gives more context.

**Comment by Denz1994** [comment]
Okay, molecules should be fixed in the above commit. I'll verify with @arouinfar.

**Comment by Denz1994** [comment]
Here are the other examples requested above:

![image](https://user-images.githubusercontent.com/13894380/91595787-1816b780-e932-11ea-9136-bc744eb62b91.png)


![image](https://user-images.githubusercontent.com/13894380/91595826-27960080-e932-11ea-86a1-61c4b16cdf8f.png)


![image](https://user-images.githubusercontent.com/13894380/91601001-e9e7a680-e936-11ea-9c4f-ef962d56764a.png)


![image](https://user-images.githubusercontent.com/13894380/91601069-0552b180-e937-11ea-97c4-aa8d440788f8.png)

**Comment by Denz1994** [comment]
@arouinfar Based on the images above do these formulas look correct? If so, we can close this issue.

**Comment by arouinfar** [comment]
@Denz1994 the screenshot for hydrogen cyanide shows `CHN` instead of `HCN`. The other examples all look good.

**Comment by Denz1994** [comment]
Apologies, I've posted an image from a broken version. Here are the proper `HCN` molecule and goal text.

![image](https://user-images.githubusercontent.com/13894380/92025905-331c6980-ed2e-11ea-83d2-629581763f74.png)

**Comment by Denz1994** [comment]
It looks like this RC has the correct ordering. Thanks for the input. Closing this one.
