### ISSUE TITLE
iPad reset all button overlaps answer box

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#210]
**Device**
iPad 6th Gen
**OS**
iPadOS 13.7
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/QA/issues/538. Appears in app and in Safari browser.
I haven't seen this on things like Win 10 Chrome, so may be exclusive to this platform. The answer box seems longer on this platform, and can brush up behind the reset all button. Seen on the first screen with the first challenge.
**Visuals**
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/92969597-84b5aa00-f43a-11ea-88ea-e2816a7c9b6b.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/92969600-854e4080-f43a-11ea-90d1-ad2b91e1991b.png)

**Comment by KatieWoe** [comment]
Tried several single levels. Several had this overlap, but none seemed to go further than this. Adding @arouinfar to see if this even needs to be addressed.

**Comment by arouinfar** [comment]
While not Chromebook, this seems related to https://github.com/phetsims/scenery/issues/935.

@KatieWoe does this happen other iOS devices? Did this happen in earlier dev/rc's? It would be helpful to know if this is a new issue or if it is device/iOS specific.

@Denz1994 looks like there is plenty of padding in the panel, so if you shave off a few px between the collection boxes, we should be able to get rid of the overlap.

**Comment by KatieWoe** [comment]
Saw on my phone and on dev.79. Sorry this got by.

**Comment by Denz1994** [comment]
I made some additional room for the resetAllButton. This means slightly moving it down and reducing some of the vertical spacing between the collection box items. This should be fixed in this [version](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-rc.3/phet/build-a-molecule_all_phet.html). Can you verify @KatieWoe or @arouinfar?

**Comment by arouinfar** [comment]
The layout looks good on my laptop, but I'll leave it to @KatieWoe to verify on iPad.

**Comment by KatieWoe** [comment]
This looks good on iPadOS 14
