### ISSUE TITLE
iPadOS 14 Molecules in 3D view don't show up

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#211]
**Device**
iPad 6th Gen
**OS**
iPadOS 14
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/QA/issues/550
Only shows up on iPadOS 14, not on iPadOS 13.7. If you build a molecule and press the 3D button, no image shows up. In either the ball model or the ball and stick model. Taking a picture seems to make it appear, but it flickers and doesn't move like it should.
**Visuals**
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/94192771-a1a3a180-fe6c-11ea-9062-8bebbff442ea.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/94192783-a49e9200-fe6c-11ea-8f13-c9d1f37f19dd.png)

**Comment by arouinfar** [comment]
This look similar to https://github.com/phetsims/charges-and-fields/issues/189

**Comment by ariel-phet** [comment]
@Denz1994 I think it would be good for @jonathanolson to be involved in this fix as it appears to be a more general issue...oh iOS updates...

**Comment by jonathanolson** [comment]
There are other issues going on, but this seems to be resolved by https://github.com/phetsims/mobius/commit/d0ab7e1ea31f37025c56038bac2df757c95fd35c, @Denz1994 can you look into BAM with this if needed? I'm investigating the CAF issues and other details of why this is necessary.

**Comment by Denz1994** [comment]
I don't have an iPad to test this out, so QA will have to take the lead on verifying this is longer an issue. I wasn't able to reproduce this issue on macOS Catalina 10.15.5 and Safari 13.1.1 or on iOS 12.4.8. Labeling for qa verification.

**Comment by arouinfar** [comment]
Looks fixed in macOS 10.15.7/Safari 14.0.

**Comment by ariel-phet** [comment]
Fixed for me in iOS 14 on iPad Air 2. I will also let QA verify, but this test can now proceed.

**Comment by KatieWoe** [comment]
This looks good in rc.4
