### ISSUE TITLE
Completing a level while viewing a previous level will not allow you to proceed

### ISSUE THREAD

**Issue by phet-steele** [phetsims/build-a-molecule#212]
1. Start a game and finish the first level.
2. Move on to the next level, and complete all but one of the answers.
3. Form the last molecule for the last answer, and use finger A to drag and hold this molecule over its answer box. Keep it hovered in place; do not let go of finger A.
4. With finger B, press the yellow arrow to transition back to level 1.

This will cancel the touch interaction on finger A (you can release finger A), and since the molecule was over the answer box, it will complete level 2 out of sight. However, there is no reward dialog, and pressing the yellow arrow to move forward to level 2 with reveal there is also not a "Next Collection" button. You are effectively prevented from proceeding to the next level without a Reset All, or completing the level all over again.

Seen on ChromeOS 13421.17.0 Chrome 86.0.4240.15. For phetsims/QA/issues/550.

![screenshot-phet-dev colorado edu-2020 09 24-16_17_54](https://user-images.githubusercontent.com/5863899/94206369-83e13700-fe82-11ea-8157-26293252a38d.png)

<details>
<summary>Troubleshooting Information</summary>

URL: https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-rc.3/phet/build-a-molecule_all_phet.html
Version: 1.0.0-rc.3 2020-09-16 23:48:35 UTC
Features missing: applicationcache, generatedcontent, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (X11; CrOS aarch64 13421.17.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.15 Safari/537.36
Language: es
Window: 1536x714
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 112)
Max viewport: 8192x8192
OES_texture_float: true
</details>

**Comment by arouinfar** [comment]
Really nice find @phet-steele! I wonder if this is a Chromebook multitouch issue or a more general multitouch issue. I think it would be helpful to know if it occurs on iOS as well. Not sure if you have access to an iPad @phet-steele so I'll co-assign @KatieWoe.

**Comment by KatieWoe** [comment]
Reproduced on iPadOS 14.0.1. Great catch!

**Comment by phet-steele** [comment]
> Not sure if you have access to an iPad @phet-steele

I do not have one. 😄

**Comment by Denz1994** [comment]
Great catch. The issue is centered around what happens to the molecules after the touch event is canceled. Because the molecule intersects with the collection box bounds and the userControlledProperty is false it will accept the molecule. I think we'll just need to check for the current kit to prevent acceptance or maybe force the molecule back to the kit. 

I have a touch device I can test this on.

**Comment by Denz1994** [comment]
The patch above makes it so molecules are only added to boxes if the kit is the currently active kit. This should handle all multi-touch cases that swap kits while dragging is still active. Will have qa verify.

**Comment by phet-steele** [comment]
@Denz1994 I am not seeing this fix present in 1.0.0-rc.4

**Comment by KatieWoe** [comment]
Issue still occurs in rc.4 on iPadOS 14 as well.

**Comment by Denz1994** [comment]
The patch above only handled cases where the kit was changed. I thought this would catch collection changes as well. Additional restrictions on dropping completed molecules have been added. This restriction limits accepted molecules to collection boxes that are part of the current active collection.

@ariel-phet asked to be assigned to this one for testing.

Can you verify this [version](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-rc.5/phet/build-a-molecule_all_phet.html) has the appropriate fix @ariel-phet?

**Comment by ariel-phet** [comment]
@phet-steele said he will have a little time for this verification

**Comment by phet-steele** [comment]
This looks fixed in 1.0.0-rc.5!
