### ISSUE TITLE
User suggestion: access to all atoms, polyatomic ions

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/build-a-molecule#215]
> Would it be possible to just have access to all atoms at once? It seems they reset as you scroll through. I would love to be able to show my students as many examples as possible, especially since we break the octet rule often in Honors and AP.
> 
> Ability to create polyatomic ions? I was trying to create ammonium and it wouldn't let me.

**Comment by arouinfar** [comment]
The file size of BAM is 2-3x larger than the typical sim. There are nearly 10,000 molecules in [otherMoleculesData.js](https://github.com/phetsims/build-a-molecule/blob/master/js/common/model/data/otherMoleculesData.js) which only includes the neutral molecules that can be built by the current bucket configurations in the sim. Rebuilding the database is very time consuming and costly. We're currently updating it in #158, but we will not be expanding it beyond the current limits. Adding ions would conservatively triple the database (imagine adding/removing a few electrons from all current molecules).

If the user is interested in the geometry of the ammonium ion or structures which violate the octet rule, I would recommend they use the Molecule Shapes sim (full, not basics). The Model screen will let them build a generic molecule with any combination of bonds/lone pairs. The Real Molecules screen will show actual examples of molecules with a variety of geometries, including those with >4 bonds on the central atom.

**Comment by oliver-phet** [comment]
Thanks so much, @arouinfar. I'll reply to the user.
