### ISSUE TITLE
Nomenclature standard 

### ISSUE THREAD

**Issue by arouinfar** [phetsims/build-a-molecule#217]
Recently, two teachers have contacted phethelp in regards to nomenclature. In both cases, the user expected the displayed name to be the common name.

| CID | IUPAC traditional name | Name on PubChem entry |
| --- | --- | --- |
| [1045](https://pubchem.ncbi.nlm.nih.gov/compound/1045) | 4-aminobutylamine | putrescine |
| [6584](https://pubchem.ncbi.nlm.nih.gov/compound/Methyl-acetate) | acetic acid methyl ester | methyl acetate |

We're currently working on updating the data set in #158, so I reached to Isam to see if these naming discrepancies would be resolved. He confirmed that we are using the IUPAC Traditional Name provided in the SDF files. In the case of [putrescine](https://pubchem.ncbi.nlm.nih.gov/compound/1045), the names provided in the SDF file are:

```
> <PUBCHEM_IUPAC_OPENEYE_NAME>
butane-1,4-diamine

> <PUBCHEM_IUPAC_CAS_NAME>
butane-1,4-diamine

> <PUBCHEM_IUPAC_NAME_MARKUP>
butane-1,4-diamine

> <PUBCHEM_IUPAC_NAME>
butane-1,4-diamine

> <PUBCHEM_IUPAC_SYSTEMATIC_NAME>
butane-1,4-diamine

> <PUBCHEM_IUPAC_TRADITIONAL_NAME>
4-aminobutylamine
```

There isn't a field for the common/preferred name displayed on the PubChem entry. However, the prevailing name seems to be butane-1,4-diamine. Perhaps we should be using the PUBCHEM_IUPAC_NAME instead?

**Comment by issamali67** [comment]
PUBCHEM_IUPAC_NAME can give "less simple" names, which may not be the preferred ones. Here is an example: CID 6585, which is peracetic acid in the current and new data bases. If we use IUPAC_NAME then it will appear as ethaneperoxoic acid, which is also the prevalent name. However, pubchem lists it under the title peracetic acid, so I guess peracetic is the preferred name (which is also PUBCHEM_IUPAC_TRADITIONAL_NAME).

**Comment by arouinfar** [comment]
Thanks for the information @issamali67. Let's stick with the `PUBCHEM_IUPAC_TRADITIONAL_NAME`. I'll be sure to make a note about the convention in the Teacher Tips.

**Comment by oliver-phet** [comment]
We received an email into phethelp about another molecule:

> Not consistently using IUPAC naming conventions e.g. butyric acid instead of butan-1-ol

But I see 'butanoic acid' listed under 2.1.1 IUPAC Name:

CID | IUPAC traditional name | Name on PubChem entry
-- | -- | --
[264](https://pubchem.ncbi.nlm.nih.gov/compound/264) | butanoic acid | Butyric Acid

**Comment by arouinfar** [comment]
@oliver-phet we use the IUPAC Traditional name, otherwise we'd see things like "oxidane" instead of "water". This is documented in the Teacher Tips.

**Comment by oliver-phet** [comment]
Thanks, replied to user!
