### ISSUE TITLE
Document why removal must be guarded, or remove the guard

### ISSUE THREAD

**Issue by samreid** [phetsims/build-a-molecule#218]
In https://github.com/phetsims/axon/issues/332 we removed the guard from createObservableArray removal methods.  I added a sim-specific guard in the following commit, but I'm not sure if it should be documented or eliminated.  Assigning to responsible dev to take a look:

https://github.com/phetsims/build-a-molecule/commit/a2cb0776b6b7914cfdb6033e027338a084167005

**Comment by Denz1994** [comment]
Guard has been removed. It isn't necessary if we remove the atom from the particle list in the `atomDragCallback` instead of in the `particleRemovedListener`. Thanks for shedding some light on this issue. Closing.
