### ISSUE TITLE
Sound coverage is spotty

### ISSUE THREAD

**Issue by jbphet** [phetsims/build-a-molecule#223]
In [version 1.0.2 of this sim](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.2/phet/build-a-molecule_en_phet.html), which is the version of the sim that is live on our site at the time of this writing, sound is enabled, I think because there was a desire to have the "ding" sound play when molecules were correctly built and captured.  Common UI sounds were used in some places, such as for the Reset All button, but they were turned off in other places.  As a result, the sound seems very inconsistent and spotty.  I think we should take a pass through this and add a few sounds for basic user interactions.  It doesn't need to be a big effort, but this is a case where I think a little bit of effort could make a big improvement.

**Comment by jbphet** [comment]
Assigning to @kathy-phet to help prioritize.

**Comment by arouinfar** [comment]
My vote would be to turn on all common UI sounds. The only components that probably don't have a common sound would be the carousel and bucket.

If a user doesn't want to listen to the sound, they can mute it. The vegas-like "ding" is nice feedback, but I wouldn't consider it a pedagogical sound that should be treated differently than other sounds.

**Comment by jbphet** [comment]
We discussed this in a design meeting on 2/18/2021 and decided that for now we should turn off the UI sounds so that the only sound will be the ding when a molecule is captured.  @jbphet will implement this on master and will propagate to the release branch.  The change will go out in an upcoming release related to the molecule DB.

**Comment by jbphet** [comment]
I have fixed this on master, and it's a simple fix, but I just asked @jonathanolson over Slack whether it was a good time to propagate this fix to the release branch and do a maintenance release, and the short answer is no.  I'll defer this, and put a reminder on my calendar to get back to it in Jan 2023.

**Comment by jbphet** [comment]
I turned off all but the "success ding" in version 1.0.16, and that version is live on the website as of this writing.  Closing.
