### ISSUE TITLE
Decide whether to turn off UI sounds on next publication

### ISSUE THREAD

**Issue by markgammon** [phetsims/build-a-molecule#227]
As part of the work done for https://github.com/phetsims/vegas/issues/77, UI sounds got turned on for this simulation.  Before the sim is published again from master, we should decide whether to turn the UI sounds off, leave them on and design and implement sounds for the rest of the interactions, or publish with a partial sound design.

If the decision is to turn them off, this can be accomplished by adding the following line to the end of the sim's `-main.js` file:

```js
  soundManager.setOutputLevelForCategory( 'user-interface', 0 );
```

**Comment by jbphet** [comment]
I wasn't aware of this issue because it wasn't assigned to me, and I'm implementing the fix for it in https://github.com/phetsims/build-a-molecule/issues/223, so I'm going to close this as a duplicate.
