### ISSUE TITLE
CT Corner overlap on left edge

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#232]
```
build-a-molecule : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-molecule/build-a-molecule_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-molecule%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661515400877%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Corner overlap on left edge
Error: Assertion failed: Corner overlap on left edge
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/assert/js/assert.js:28:13)
at assert (Shape.js:2037:14)
at roundedRectangleWithRadii (RectangularButton.ts:204:15)
at createButtonShape (RectangularButton.ts:175:33)
at callback (Multilink.ts:111:10)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:303:22)
at _notifyListeners (ReadOnlyProperty.ts:254:13)
at unguardedSet (ReadOnlyProperty.ts:238:11)
at set (DerivedProperty.ts:155:12)
id: Bayes Puppeteer
Snapshot from 8/26/2022, 3:59:33 AM
```

**Comment by samreid** [comment]
This was introduced by the new layout changes. The content of the button for ?stringTest=xss is only 6.7 but the corner radii are 4, so it is not able to curve the button as requested.  Turning off the button curvature leads to a similar problem in the gradient.

After fixing those, there is still a layout problem like so:

<img width="383" alt="image" src="https://user-images.githubusercontent.com/679486/187038285-fa43084a-1207-412c-a7af-80393b3e07cb.png">

Still, I'll commit this workaround until we can get to the root of the problem.

**Comment by jonathanolson** [comment]
It looks like the corner radius limit was added in https://github.com/phetsims/under-pressure/issues/151, so I can now remove the corner-radius ternary and get this:

<img width="317" alt="image" src="https://github.com/user-attachments/assets/20b3a30f-9d6b-4c78-a43c-c5f06bfa09da">

More realistic strings would be like:

<img width="283" alt="image" src="https://github.com/user-attachments/assets/723131a7-2904-4726-b48b-dbb0e4c0535b">

Is there anything else to do here? Pushed the corner-radius change for the button above.

**Comment by samreid** [comment]
That looks great, thanks! Closing.
