### ISSUE TITLE
Cutoff home screen with Hungarian

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/build-a-molecule#27]
Will cross-post to Joist. Here's the screenshot:
![bam-hungarian-home-cutoff](https://f.cloud.github.com/assets/480878/1341410/cd89c5a2-3648-11e3-8fa2-9f512e58509f.PNG)

**Comment by Denz1994** [comment]
Tested with stringTest=long. Home screen strings aren't trailing off of the screen anymore. Closing.
