### ISSUE TITLE
Touch area overlapping in Korean

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/build-a-molecule#28]
See screenshot.

![bam-korean-touch-overlap](https://f.cloud.github.com/assets/480878/1341426/3d49e6ba-3649-11e3-9f7f-04133e0c1b9b.PNG)

**Comment by Denz1994** [comment]
There are still some optimizations to be done for strings. Maxwidths need to be adjusted so they aren't overlapping or expanding bounds of panels. I'm going to close this issue because it isn't locale-specific.
