### ISSUE TITLE
Ghost molecule + dotted outline (1st time)

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/build-a-molecule#32]

**Comment by Denz1994** [comment]
From the java version: The first time a collection box molecule is created a rather larger arrow and a message appears to direct the user to drop it into the box.

It is suggested that a more subtle indication is provided to guide the user.

Suggestions:
1. https://github.com/phetsims/build-a-molecule/issues/32#issuecomment-26553690
2. Text inside the collection box reading "Drag Here", that fades after an atom is dragged. Similarly to the Area-Builder game screen, which reads "Your goal: "
3. Leave as is, with the blue highlight as enough of an indication.

Thoughts @ariel-phet?

**Comment by Denz1994** [comment]
It was discussed during the design meeting on 11/27/19, that we would have a flashing box for the first molecule, highlighted box for subsequent molecules.

This has been implemented in this dev version [0.0.1-dev.28](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.28/phet/build-a-molecule_en_phet.html). It is still up for debate on what we want the subsequent highlights to look like.

Some suggestions included behavior similar to Expression-Exchange.

**Comment by arouinfar** [comment]
In the 12/5/19 design meeting, we decided to try a cueing arrow that points to the box when the corresponding molecule has been built in the play area. The arrow will be appear when the molecule is built, and will stay visible until the molecule has been dragged into the collection box. If there are multiple target molecules built in the play area, there will will be multiple arrows. 
![image](https://user-images.githubusercontent.com/8419308/70364051-2115a500-1848-11ea-8b83-12001fb0a38c.png)

**Comment by arouinfar** [comment]
@ariel-phet how does this look?

**Comment by Denz1994** [comment]
Upping priority for input on visuals related to https://github.com/phetsims/build-a-molecule/issues/32#issuecomment-562790082.

**Comment by ariel-phet** [comment]
All visuals look good to me. Marking for design meeting, since it would be good to get @kathy-phet sign off

**Comment by Denz1994** [comment]
Discussed from design meeting on 02/06/20:

It was decided to revise the curing behavior. The desired behavior is for the arrow and blinking highlight to only appear on the first kit of the kit collection. They should not appear at all on any other collection. The highlight and cue should show until the first item is added in the box.

**Comment by Denz1994** [comment]
This [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.56/phet/build-a-molecule_all_phet.html) has the above changes. Can you review @arouinfar and comment on the behavior of the Multiple screen cueing?

**Comment by Denz1994** [comment]
Minor tweak to the order of reset callbacks for the resetCollectionButton. There was a bug where the arrow would remain visible after clicking the resetCollectionButton if valid molecules were left in the kit play area.

 That change is now on Master, it is **NOT** the dev version posted above @arouinfar.

**Comment by arouinfar** [comment]
@Denz1994 there are a few issues with the cueing behavior.

General rules
* Blue cueing box/arrow appears on Collection 1 only (current behavior is correct)
* Cueing should only appear until one of the collection boxes is filled 
   * Single screen: cueing stops after first item added to collection box
   * Multiple screen: cueing stops after the first target is completely filled & yellow stroke appears
* Until the above condition is satisfied, the blue box/arrow will appear each time a target molecule is built.  
* Each time a collection box is filled, a yellow stroke will appear and the ding will play, regardless of collection number (current behavior is correct)

I think the behavior is also somewhat buggy. If I don't drag an item into the Collection box, the cue plays each time a target molecule is built (this is correct). After the flashing ends, the blue arrow continues to point to the most recently built target molecule (seems reasonable). However, if edit a molecule in the play area (not the one currently being cued) the arrow will disappear, which seems odd to me.

Example:
1. Single Screen, Kit 2
2. Build O2. Cue appears as expected. 
3. Build H2. Cue appears as expected.
4. Sever O2, and the cueing arrow on H2 disappears. This seems buggy.
![cue](https://user-images.githubusercontent.com/8419308/74567537-40f5d300-4f33-11ea-9921-b6df23d09952.gif)

Things can also get weird when switching between kits. The cueing arrow for a molecule not currently in the play area will remain.

Example:
1. Singe Screen, Kit 2
2. Build O2.
3. Switch to Kit 3. Cueing arrow remains on O2 collection box, but O2 is not currently visible in the play area. (Cueing arrow should disappear when switching kits.)
4. Build N2. O2 cueing arrow disappears when grabbing the first N which makes it seems like the sim known O2 isn't actually in the play area.
5. Switch back to Kit 2. Cueing arrow for N2 remains, despite not being in the play area.
![cue2](https://user-images.githubusercontent.com/8419308/74568073-6fc07900-4f34-11ea-952d-7319915d3883.gif)

**Comment by Denz1994** [comment]
The logic for the cueing has been reworked. Most of the changes involve, updating the kit emitters for adding/removing molecules. We also need to check for valid molecules when switching kits. The buggy example mentioned above should be resolved.

This [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.70/phet/build-a-molecule_en_phet.html), follows the guidelines provided from above. It would be worth reviewing @arouinfar.

**Comment by Denz1994** [comment]
From a conversation on slack with @arouinfar: 

> I can't remember if we decided if the box should flash every time a molecule is correctly built until something is added to a collection box. Currently, the box only flashes for the first correctly built molecule, regardless of what is added to the collection.

My reply via slack:

> I couldn’t find a paper trail for that decision, just personal notes that imply that the blinking behavior shouldn’t change after refactoring the arrow cues. This dev version will cause the box to blink every time a molecule is added/removed from the play area until one box is filled with something.
> At times the blinking can become excessive. Like on Screen 1 , Kit 3:
> 1. Build O2 and N2 but don’t add it to the box
> 2. Drag out the last Carbon (the boxes will blink)
> 3. If you quickly add and remove that carbon in and out of the carousel, the blinking continues.

The dev version for comparison can be found [here](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.71/phet/build-a-molecule_all_phet.html).

**Comment by arouinfar** [comment]
@Denz1994 thanks for implementing this in dev.71. It was a really helpful comparison! I think the blinking was a little buggy, but it was close enough to get the idea across. I agree that the blinking can become excessive, so let's stick with the behavior in dev.70.

**Comment by Denz1994** [comment]
Good to know. I'll revert to match dev.70. Thanks for the review.

**Comment by Denz1994** [comment]
Changes have been reverted back to dev.70 and a new dev version has been pushed [here](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-dev.71/phet/build-a-molecule_all_phet.html).

Thanks @arouinfar closing this one.
