### ISSUE TITLE
iOS Safari Performance slows when dragging molecules outside other's bounds

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/build-a-molecule#34]
To test, pull out a bunch of molecules on the 3rd screen. Then drag around a molecule. It's fast when the bounding box of the molecules isn't changing, and slow when it is (even though we are using SVG).

Maybe a no-fill no-stroke rectangle can speed up performance in this case?

**Comment by Denz1994** [comment]
Drag hasn't been noted as being slow or laggy. It is also worth noting that we are now using `DragListeners`. Will reopen if this becomes an issue.
