### ISSUE TITLE
Slice sound effect

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/build-a-molecule#40]

**Comment by Denz1994** [comment]
With the recent changes to common code components (seen [here](https://github.com/phetsims/tambo/issues/73)), the sim now has a lot more sound playing. It may be worth adding a slicing sound effect. 

I don't know if this should be the same sound that the separation button makes. Maybe a swoosh or chop sound? Thoughts @ariel-phet?

**Comment by ariel-phet** [comment]
Deferred until we decide how to deal with separating individual bonds

**Comment by Denz1994** [comment]
The separation button uses a press listener and has an associated sound with the common code component. The slice node referred to in the [comment](https://github.com/phetsims/build-a-molecule/issues/40#issuecomment-556540047) above, has been removed as a part of #52.

This issue can be closed.
