### ISSUE TITLE
Slicing multiple bonds should be atomic

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/build-a-molecule#44]
Breaking apart H2O2 with a slice should never cause an O2 collection box to flash.

**Comment by Denz1994** [comment]
This was tested on the first kit collection on the Singles screen. Tested by creating hydrogen peroxide and cutting bonds in this order: Hydrogen-Oxygen, Hydrogen-Oxygen, Oxygen-Oxygen.

Using one slice stroke, the collection box didn't flash as if Molecular Oxygen (O2) was created.
Closing this issue.
