### ISSUE TITLE
Crisper 3D / split buttons

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/build-a-molecule#48]
Might be best to just do the background / shapes in Scenery.

**Comment by Denz1994** [comment]
Buttons were replaced by Scenery elements. This includes the `ResetAllButton`, `ShowMolecule3DButtonNode`,  `RefillButton`, and `NextCollectionButton`.  The sound button was removed and now uses the nav-bar icon to support toggling sound.

Closing.
