### ISSUE TITLE
Thicker smoother slice line

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/build-a-molecule#52]
Possibly ghosting, softer but fruit-ninja-esque.

**Comment by Denz1994** [comment]
@ariel-phet The slice node was given a slightly thicker line but it would be good to settle if we want changes in the final version.

**Comment by ariel-phet** [comment]
Unclear if we want to use this kind of slicing action or a different bond separation paradigm. Deferring until we figure that out.

**Comment by Denz1994** [comment]
Labeling for the next design meeting to continue the discussion. We should also consider #146.

**Comment by Denz1994** [comment]
From design meeting 01/31/20:

The design team is on board with removing this feature for a few reasons. It isn't obvious that it is possible to draw a slice node to break bonds. Slicing can happen by accident while trying to drag the molecule. Additionally, the ability to draw freely in the play area should be limited.

**Comment by Denz1994** [comment]
The slice node along with has been removed as a feature. Closing this issue.
