### ISSUE TITLE
Homescreen/navbar icons

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/build-a-molecule#55]

**Comment by Denz1994** [comment]
The first two screens operate like a game with goals to create single or multiple same-type molecules. The third screen functions like a sandbox for users to experiment with building molecules.

@arouinfar and @ariel-phet Thoughts on icons to represent this?

**Comment by ariel-phet** [comment]
Discussed today with @Denz1994 thinking of creating these programmatically.

1st screen - Water (3d style)
2nd screen - 2 sets of oxygen molecules (3d style)
3rd screen - vinegar (3d style)

**Comment by arouinfar** [comment]
@Denz1994, here's what acetic acid (vinegar) looks like
![image](https://user-images.githubusercontent.com/8419308/69754899-443ba880-1114-11ea-9df3-ccc7617315d6.png)
![image](https://user-images.githubusercontent.com/8419308/69754918-51f12e00-1114-11ea-9c72-d5846f698be4.png)

**Comment by Denz1994** [comment]
This [dev version](url) should have the latest homescreen/navbar icons @arouinfar. How would you like the two sets of O2 oriented? Should they be stacked vertically, or horizontally (like in the collection box layout)?

**Comment by arouinfar** [comment]
@Denz1994 the Single and Playground icons look great. For Multiple, let's try two side-by-side oxygen molecules. I think it'd be a nice parallel to the collection box.

**Comment by Denz1994** [comment]
Master has been updated with the above suggestion for the Multiple Screen. Could you review @arouinfar?

**Comment by arouinfar** [comment]
@Denz1994 looks pretty good, but the alignment of the molecule within the icon could be cleaned up.  Can you center the molecules vertically and horizontally? For Multiple, the relative position of the molecules is good, but the group alignment looks off.
<img src="https://user-images.githubusercontent.com/8419308/72930825-09bc4980-3d1a-11ea-8d2f-01d84cf343a4.png" width=200><img src="https://user-images.githubusercontent.com/8419308/72930838-117bee00-3d1a-11ea-85c6-7b8f74740b55.png" width=200><img src="https://user-images.githubusercontent.com/8419308/72930854-18a2fc00-3d1a-11ea-96e1-407caeddd36f.png" width=200>

**Comment by Denz1994** [comment]
Could you review this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.49/phet/build-a-molecule_all_phet.html) @arouinfar for the alignment changes?

**Comment by arouinfar** [comment]
Looking pretty good @Denz1994, but the alignment of the acetic acid molecule in Playground is still looking a bit vertically off-center. Can you shift the molecule up a bit?
![image](https://user-images.githubusercontent.com/8419308/73288279-ed0b9000-41b7-11ea-9cdf-7afdd925bfb7.png)

**Comment by Denz1994** [comment]
Could you review master @arouinfar? The playground icon has been adjusted.

**Comment by arouinfar** [comment]
Looks great @Denz1994
