### ISSUE TITLE
Bucket labels should be white

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/build-a-molecule#56]
Potentially adjust bucket gradients for visibility.

**Comment by Denz1994** [comment]
Bucket labels are made white to contrast with darker backgrounds. This is the same for atomNode labels.
See `AtomNode.getTextColor()`.

![image](https://user-images.githubusercontent.com/13894380/69236256-23e27b80-0b61-11ea-934d-653f3fbfb4bf.png)
