### ISSUE TITLE
Add non-wrapping carousel

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/build-a-molecule#57]
Mock up arrows (right-angle style, black/grey fill with width to work)

Status circles should also be clickable. Consider top-left and bottom-center.

Swipe to switch between kits - damped motion system.

**Comment by Denz1994** [comment]
Scenery-PhET's carousel has been added to all screens. It swaps between kits in the kitCollection and contains the buckets with atoms. There is no longer a need to label the kits (i.e. Kit #1).

Closing.
