### ISSUE TITLE
Iconinize the refill kit button

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/build-a-molecule#58]
Barebones simple (bucket shape with circles on top).

**Comment by Denz1994** [comment]
The refill button is currently a bucket with "Refill" text, which works well as is. I don't think it is necessary for this sim to have an icon but I'll double-check with @ariel-phet.

**Comment by Denz1994** [comment]
As part of design meeting 11/27/19:

The idea is to have an atom going into a bucket. This should be handled well with a Shape built inside the button.

**Comment by Denz1994** [comment]
Did you have a mockup in mind for this @arouinfar?

**Comment by arouinfar** [comment]
I've mocked up a few options for an iconic button. We could also consider using a local reset, but I think it would only be appropriate if we decide to place the button on top of the carousel. At scale, I think the 2nd option is the easiest to read, so I've used it in the placement mockups below.
![image](https://user-images.githubusercontent.com/8419308/73093808-8a0ab800-3e9c-11ea-8e55-608a43065f11.png)

For the button placement, we considered placing it within (or technically on top of) the carousel. I've mocked this up for the most crowded carousel. I think it'd be doable, but perhaps not ideal. I'd prefer to leave the button in its current location.
![image](https://user-images.githubusercontent.com/8419308/73093875-ac043a80-3e9c-11ea-87d8-e17c89405744.png)
![image](https://user-images.githubusercontent.com/8419308/73093917-c8a07280-3e9c-11ea-87d7-5e6bd429061c.png)
![image](https://user-images.githubusercontent.com/8419308/73093960-df46c980-3e9c-11ea-9e4a-339e9b24a395.png)

Assigning to @ariel-phet for review.

**Comment by arouinfar** [comment]
The buttons in the mockups in https://github.com/phetsims/build-a-molecule/issues/58#issuecomment-578248931 are 40x40 px.

We could probably reduce the button to 30x30 px, but the icon will be a bit harder to read.
![image](https://user-images.githubusercontent.com/8419308/73103550-8cc3d800-3eb1-11ea-8ffe-f05ff48d3292.png)

**Comment by ariel-phet** [comment]
The button in its current location (left aligned above the carousel) seems best

**Comment by Denz1994** [comment]
The current implementation is built using a sample `Bucket` with `BucketHole` and `BucketFront` visuals. 

The arrow is using FontAwesome's [Reply arrow](https://fontawesome.com/icons/reply?style=solid). There is a bit more of a curve at the base of the arrow, but this is the closest we can get without building a specific arrow using `Path`. I opted into using FontAwesome in light of reusing common code. 

Does this look okay @arouinfar? Review in this [dev version](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.51/phet/build-a-molecule_all_phet.html).

**Comment by Denz1994** [comment]
From design meeting on 01/31/20

The design team agrees the current implementation looks great as is. @ariel-phet suggested extending the size by 10px from the top-right corner.

**Comment by Denz1994** [comment]
The refill button size has been increased. Just for context the hydrogen atom now fits well within the size of the refill button. Closing this issue.
