### ISSUE TITLE
replace MeterBodyNode with ShadedRectangle

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/build-a-molecule#66]
molecule-shapes is the only client of scenery-phet.MeterBodyNode, it's been replaced with scenery-phet.ShadedRectangle in all other sims. I've marked MeterBodyNode as deprecated. When you've switched over to ShadedRectangle, please delete MeterBodyNode.

**Comment by Denz1994** [comment]
There is no longer any usages of `MeterBodyNode`or `ShadedRectangle`. There is only the use of `ShadedSphereNode`. This issue can be closed.
