### ISSUE TITLE
Uncaught TypeError on startup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/build-a-molecule#68]
I was about to change 'BAM' to 'BUILD_A_MOLECULE' throughout, to address #69. But before doing so, I noticed that this sim is throwing an error at startup. I'm running out of master, and this does not appear to be OS or browser specific. Here's the stack trace:

 Uncaught TypeError: Cannot set property id of [object Object] which has only a getterPropertySet.js?1421437006049:60 PropertySetNextPreviousNavigationNode.js?1421437006049:39 NextPreviousNavigationNodeCollectionPanel.js?1421437006049:74 CollectionPanelCollectionPanel.js?1421437006049:152 CollectionPanel.getCollectionPanelModelWidthbuild-a-molecule-main.js?1421437006049:92 (anonymous function)SimLauncher.js?1421437006049:30 doneLoadingImagesSimLauncher.js?1421437006049:50 launchbuild-a-molecule-main.js?1421437006049:88 (anonymous function)

**Comment by pixelzoom** [comment]
Calling 2 supertype constructors in NextPreviousNavigationNode.  Unless one of these was designed as a mixing, this is generally dangerous.  I'm guessing that it worked at one time, and some change to either PropertySet or Node broke it.

```js
    PropertySet.call( this, {
      hasNext: false,
      hasPrevious: false
    } );
    Node.call( this, {} );
``

**Comment by jonathanolson** [comment]
It will be an even more dangerous fix for Scenery 0.2, where nodes mix in Events, which PropertySet extends. I'll plan on using composition for the property set or using individual properties.

**Comment by pixelzoom** [comment]
Since this is a problem in a common-code component (scenery-phet.NextPreviousNavigationNode),  I took the liberty of fixing it. I removed the PropertySet, used individual Properties, and update client code (build-a-molecule was the only client).

Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Doh, had fixed when I didn't have internet (airport), saw merge conflicts and backed everything out.

We probably want a way to add a PropertySet-like property (ES5 getters/setters are more convenient) without something being a PropertySet. Also notably, .id was added to PropertySet, making it incompatible to mix into any Node.

Changes look fine, closing.

**Comment by samreid** [comment]
lint errors, i'll push fix shortly

**Comment by samreid** [comment]
Fixed above, closing.
