### ISSUE TITLE
change BAM to BUILD_A_MOLECULE

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/build-a-molecule#69]
There's no reason that this sim should be using a different convention, and it's resulting in BAM-specific code in the string.js plugin (see https://github.com/phetsims/chipper/issues/83).  Please change BAM to BUILD_A_MOLECULE throughout.

**Comment by jonathanolson** [comment]
There's no reason extra logic should be required in the string.js plugin (namespace should be included in package.json), but if it significantly simplifies things I can make the conversion.

Long-term, it's annoying to need to type many more characters for imports (can be ~5kB worth of additional characters)

**Comment by pixelzoom** [comment]
> it's annoying to need to type many more characters for imports 

Then use a live template (if you're using IDEA) or similar 'macro' expansion in whatever editor you're using.

**Comment by pixelzoom** [comment]
I also don't think that string.js has any business knowing about package.json, for sims or dependencies.

**Comment by pixelzoom** [comment]
#68 is fixed, so I completed this issue. closing.
