### ISSUE TITLE
Fix startup performance

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/build-a-molecule#7]
It's very slow, sometimes ~20 seconds on the iPad. This can consist of:
- Delay reading / computing all structures initially, just the ones needed for display.
- More compact way of storing molecule data, or pre-compress

**Comment by Denz1994** [comment]
It has been noted that start up time isn't an issue and performance issues haven't been reported in the latest dev-test. See here: https://github.com/phetsims/build-a-molecule/issues/109.

**Comment by lmulhall-phet** [comment]
As of today (2020-01-23), I would say the startup time is a bit long.

Testing BAM on master gave the following results. (These times were measured from hitting the reload page button to the time the home screen was loaded.)

| Device                        | Time (s) |
|-------------------------------|----------|
| newish macOS (my MacBook Air) | 8.49     |
| newish Win10 (Logan's Lenovo) | 15.79    |
| newish iOS (my iPhone SE)     | 13.7     |

**Comment by lmulhall-phet** [comment]
@Denz1994, I just tested https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.47/phet/build-a-molecule_en_phet.html and the performance was much faster on all the above platforms. Load time took ~5 seconds on all platforms, and this seems acceptable.

**Comment by Denz1994** [comment]
Thanks for double-checking on the start up time. Closing this one.
