### ISSUE TITLE
directory structure violates PhET convention

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/build-a-molecule#70]
Source-code directory structure for a 1-screen sim should look like this:

``` js
js/
 build-a-molecule/
    model/
    view/
```

**Comment by jonathanolson** [comment]
Is this also requesting the 'control' items moved to the 'view' directory? Or just adding the top-level JS directory 'build-a-molecule'?

**Comment by pixelzoom** [comment]
Just adding the top-level build-a-molecule dir for the 1 screen.  I don't care too much about whether controls are in view or their own dir.

**Comment by Denz1994** [comment]
This issue is stale. This sim has 3 screens now and the directory structure has been fixed in https://github.com/phetsims/build-a-molecule/issues/129
