### ISSUE TITLE
remove chipper from phetLibs in package.json

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/build-a-molecule#71]
chipper is automatically added as a dependency at build time. 

See chipper.Gruntfile.js, line 498:

``` js
    var dependencies = pkg.phetLibs.split( ' ' );
    if ( dependencies.indexOf( 'chipper' ) === -1 ) {
      dependencies.push( 'chipper' );
    }
```

**Comment by pixelzoom** [comment]
Actually... I guess it's not hurting anything by having chipper in package.json.  But no other sims include it.

**Comment by Denz1994** [comment]
Chipper was removed from phetLibs in the package.json by this commit 91013a71a92b8b974019a99ca30b236222b963f8. Closing.
