### ISSUE TITLE
potential problem with mutable bounds

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/build-a-molecule#73]
This may be a problem with mutable bounds.

CollectionAreaNode, line 85:
> resetCollectionButton.touchArea = Shape.bounds( resetCollectionButton.bounds.dilate( 7 ) );

Recommended to use `dilated`. I see `dilated` used elsewhere throughout the sim, so I'm guessing this is a typo.

**Comment by jonathanolson** [comment]
Thanks for catching this! Fixed.
