### ISSUE TITLE
Annotate license.json

### ISSUE THREAD

**Issue by samreid** [phetsims/build-a-molecule#75]
This simulation has many images that are not annotated in the license.txt, either in the JS or Java version.  I'm unfamiliar with the sim and I don't know which images we drew ourselves vs used from a 3rd party.  Please annotate.

**Comment by samreid** [comment]
I added empty stubs above for the license.json file.  This is currently the only project that is not building, and is causing difficulty for the licensing project, which requires sims to build in order to harvest their license data.  I have workarounds in place but it would be good to resolve this soon.

**Comment by pixelzoom** [comment]
I hit this again today. And the build fails now that we've added license checking.  Raising priority to high.

**Comment by jonathanolson** [comment]
Let me know if there's anything else that should be done here (like the modified/converted scissors images being noted as derived works?).

**Comment by samreid** [comment]
Added text above.

**Comment by samreid** [comment]
Everything else looks good, thanks. Closing.
