### ISSUE TITLE
use standard PhET namespace

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/build-a-molecule#78]
This sim appears to have its own non-standard namespace (see namespace.js), so it wasn't easily addressed when adding a standard PhET namespace to other sims in https://github.com/phetsims/joist/issues/307.  @jonathanolson will need to handle this.

This sim will continue to fail automated testing until this is addressed.

**Comment by Denz1994** [comment]
This issue is stale. Automated testing hasn't been failing due to namespace issues.
