### ISSUE TITLE
Disabled carousel scrolling animation.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/build-a-molecule#99]
The scrolling animation for the kit area carousel has been disabled. The legacy kit area component didn't support this animation, but I'm not sure if that was a design decision. This issue is opened to settle on disabling the scrolling animation. Consider that Area-Builder, CCK, and Expression-Exchange use the scrolling animation.

If we do go ahead with using the animation, we should decide how the play area is swapped. Should the play area instantly swap to anther kit or transition? I'm thinking of a transition similar to what we use in games Make-a-Ten or Equality-Explorer/Solve-It using a TransitionNode. This transition would only include the molecules. Thoughts @ariel-phet.

**Comment by ariel-phet** [comment]
Discussed with @Denz1994, this issue is a bit more of a polish, but using a transition does seem like it would be nicer. Marking as a polish, since it should be done when the rest of the sim is fully functional.

**Comment by Denz1994** [comment]
Note: While the carousel is animating kits in and out of its view, the atom can be grabbed. This means that a user can grab an atom from a bucket while the play area is transitioning to the next kit.

Potential solution: Disable the pickability of atoms during the animation cycle. Does Carousel.js have support for this behavior?

Hacky alternative: Shorten the duration of the carousel animation, so it unlikely a user will grab an atom from the buck during the animation cycle. 

This will require testing on multi-touch to see how much of a nuisance this is (hard to reproduce with a mouse). The transition node's animation should match the duration of the carousel.

**Comment by Denz1994** [comment]
From design meeting 01/31/20:

The design team is on board with removing the animation due to its simplicity. Also on the Playground screen, the carousel pages don't share equal negative space in regards to the buckets and the vertical edges of the carousel.

This is most evident on the 3rd and 5th pages. We will opt out of animating the carousel pages and the play area. Closing this issue.
